import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Navigator from './Navigator';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function AccountLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header nav={<Navigator />} getStarted={false} />
      {children}
      <Footer />
    </>
  );
}
