import { QueryRunner } from 'typeorm';

import Seeder from './Seeder';

import { Breed } from '@/entities';
import { Size } from '@/enums';

export default class BreedSeeder extends Seeder {
  /**
   * Clean the Collection
   */
  async clean(queryRunner: QueryRunner): Promise<void> {
    const breedRepository = queryRunner.manager.getRepository(Breed);
    await breedRepository.remove(await breedRepository.find());
  }

  async run(queryRunner: QueryRunner): Promise<void> {
    const breedRepository = queryRunner.manager.getRepository(Breed);

    const breeds = [
      breedRepository.create({ name: 'Affenpinscher', size: Size.Small, uid: '1' }),
      breedRepository.create({ name: 'Afghan Hound', size: Size.Large, uid: '2' }),
      breedRepository.create({ name: 'Afghan Shepherd', size: Size.Large, uid: '309 - B' }),
      breedRepository.create({ name: 'Africanis', size: Size.Large, uid: '3' }),
      breedRepository.create({ name: 'Aidi', size: Size.Medium, uid: '4 - A' }),
      breedRepository.create({ name: 'Airedale Terrier', size: Size.Medium, uid: '5' }),
      breedRepository.create({ name: 'Akbash', size: Size.Large, uid: '6' }),
      breedRepository.create({ name: 'Akita (American)', size: Size.Large, uid: '7' }),
      breedRepository.create({ name: 'Akita (Japanese)', size: Size.Large, uid: '8' }),
      breedRepository.create({ name: 'Aksaray Malaklisi', size: Size.Large, uid: '9 - A' }),
      breedRepository.create({ name: 'Alano Espanol', size: Size.Large, uid: '10' }),
      breedRepository.create({ name: 'Alapaha Blue Blood Bulldog', size: Size.Large, uid: '11' }),
      breedRepository.create({ name: 'Alaskan Husky', size: Size.Medium, uid: '12' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Toy)', size: Size.Small, uid: '13' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Miniature)', size: Size.Small, uid: '14' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Standard)', size: Size.Small, uid: '15' }),
      breedRepository.create({ name: 'Alaskan Malador', size: Size.Large, uid: '9940' }),
      breedRepository.create({ name: 'Alaskan Malamute', size: Size.Large, uid: '16' }),
      breedRepository.create({ name: 'Alentejo Mastiff', size: Size.Large, uid: '418 - B' }),
      breedRepository.create({ name: 'Alopekis', size: Size.Small, uid: '17' }),
      breedRepository.create({ name: 'Alpine Dachsbracke', size: Size.Medium, uid: '18' }),
      breedRepository.create({ name: 'Altamaha Plantation Dog', size: Size.Large, uid: '38 - B' }),
      breedRepository.create({ name: 'American Alsatian', size: Size.Large, uid: '19' }),
      breedRepository.create({ name: 'American Bulldog', size: Size.Large, uid: '20' }),
      breedRepository.create({ name: 'American Bully (Pocket)', size: Size.Medium, uid: '21' }),
      breedRepository.create({
        name: 'American Bully (Standard / Classic)',
        size: Size.Large,
        uid: '22',
      }),
      breedRepository.create({ name: 'American Bully (XL)', size: Size.Large, uid: '23' }),
      breedRepository.create({ name: 'American Cocker Spaniel', size: Size.Small, uid: '24' }),
      breedRepository.create({
        name: 'American English Coonhound',
        size: Size.Large,
        uid: '26 - A',
      }),
      breedRepository.create({
        name: 'American Eskimo Dog (Toy / Miniature)',
        size: Size.Small,
        uid: '27',
      }),
      breedRepository.create({
        name: 'American Eskimo Dog (Standard)',
        size: Size.Medium,
        uid: '28',
      }),
      breedRepository.create({ name: 'American Foxhound', size: Size.Large, uid: '29' }),
      breedRepository.create({ name: 'American Hairless Terrier', size: Size.Small, uid: '30' }),
      breedRepository.create({ name: 'American Leopard Hound', size: Size.Large, uid: '31' }),
      breedRepository.create({ name: 'American Mastiff', size: Size.Large, uid: '32' }),
      breedRepository.create({ name: 'American Pit Bull Terrier', size: Size.Medium, uid: '33' }),
      breedRepository.create({
        name: 'American Staffordshire Terrier',
        size: Size.Large,
        uid: '34',
      }),
      breedRepository.create({ name: 'American Water Spaniel', size: Size.Medium, uid: '35' }),
      breedRepository.create({ name: 'American White Shepherd', size: Size.Large, uid: '84 - D' }),
      breedRepository.create({ name: 'Anatolian Karabash Dog', size: Size.Large, uid: '36 - B' }),
      breedRepository.create({ name: 'Anatolian Shepherd', size: Size.Large, uid: '36 - A' }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Small)',
        size: Size.Small,
        uid: '385 - B',
      }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Medium)',
        size: Size.Medium,
        uid: '386 - B',
      }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Large)',
        size: Size.Large,
        uid: '387 - B',
      }),
      breedRepository.create({
        name: 'Anglo-Francais de Petite Venerie',
        size: Size.Medium,
        uid: '37 - A',
      }),
      breedRepository.create({ name: 'Antebellum Bulldog', size: Size.Large, uid: '38 - A' }),
      breedRepository.create({ name: 'Appenzell Cattle Dog', size: Size.Large, uid: '39 - C' }),
      breedRepository.create({ name: 'Appenzeller Mountain Dog', size: Size.Large, uid: '39 - B' }),
      breedRepository.create({ name: 'Appenzeller Sennenhund', size: Size.Large, uid: '39 - A' }),
      breedRepository.create({ name: 'Argentine Pila (Small)', size: Size.Small, uid: '40' }),
      breedRepository.create({ name: 'Argentine Pila (Medium)', size: Size.Small, uid: '41' }),
      breedRepository.create({ name: 'Argentine Pila (Large)', size: Size.Medium, uid: '42' }),
      breedRepository.create({ name: 'Ariege Hound', size: Size.Large, uid: '44 - B' }),
      breedRepository.create({ name: 'Ariege Pointer', size: Size.Large, uid: '43 - A' }),
      breedRepository.create({ name: 'Ariegeois', size: Size.Large, uid: '44 - A' }),
      breedRepository.create({ name: 'Armant', size: Size.Medium, uid: '45' }),
      breedRepository.create({ name: 'Armenian Gampr', size: Size.Large, uid: '46' }),
      breedRepository.create({ name: 'Artois Hound', size: Size.Large, uid: '47 - A' }),
      breedRepository.create({ name: 'Atlas Mountain Dog', size: Size.Medium, uid: '4 - B' }),
      breedRepository.create({
        name: 'Aussiedoodle (Toy / Miniature)',
        size: Size.Small,
        uid: '9941 - A',
      }),
      breedRepository.create({
        name: 'Aussiedoodle (Standard)',
        size: Size.Large,
        uid: '9942 - A',
      }),
      breedRepository.create({
        name: 'Aussiepoo (Toy / Miniature)',
        size: Size.Small,
        uid: '9941 - B',
      }),
      breedRepository.create({ name: 'Aussiepoo (Standard)', size: Size.Large, uid: '9942 - B' }),
      breedRepository.create({ name: 'Australian Cattle Dog', size: Size.Medium, uid: '48 - A' }),
      breedRepository.create({
        name: 'Australian Cobberdog (Miniature)',
        size: Size.Small,
        uid: '9970 - B',
      }),
      breedRepository.create({
        name: 'Australian Cobberdog (Medium)',
        size: Size.Medium,
        uid: '9971 - B',
      }),
      breedRepository.create({
        name: 'Australian Cobberdog (Standard)',
        size: Size.Large,
        uid: '9972 - B',
      }),
      breedRepository.create({ name: 'Australian Kelpie', size: Size.Medium, uid: '49' }),
      breedRepository.create({ name: 'Australian Koolie', size: Size.Medium, uid: '50' }),
      breedRepository.create({
        name: 'Australian Shepherd (Toy / Miniature)',
        size: Size.Small,
        uid: '51 - B',
      }),
      breedRepository.create({
        name: 'Australian Shepherd (Standard)',
        size: Size.Medium,
        uid: '52',
      }),
      breedRepository.create({
        name: 'Australian Stumpy Tail Cattle Dog',
        size: Size.Medium,
        uid: '53',
      }),
      breedRepository.create({ name: 'Australian Terrier', size: Size.Small, uid: '54' }),
      breedRepository.create({
        name: 'Austrian Black and Tan Hound',
        size: Size.Medium,
        uid: '55',
      }),
      breedRepository.create({ name: 'Austrian Pinscher', size: Size.Medium, uid: '56' }),
      breedRepository.create({ name: 'Auvergne Pointer', size: Size.Medium, uid: '57 - A' }),
      breedRepository.create({ name: 'Azawakh', size: Size.Medium, uid: '58 - A' }),
      breedRepository.create({ name: 'Bac Ha Dog', size: Size.Medium, uid: '59 - A' }),
      breedRepository.create({ name: 'Bakharwal', size: Size.Large, uid: '60' }),
      breedRepository.create({ name: 'Bankhar Dog', size: Size.Large, uid: '61' }),
      breedRepository.create({ name: 'Barak Hound', size: Size.Medium, uid: '62 - A' }),
      breedRepository.create({ name: 'Barbado da Terceira', size: Size.Medium, uid: '63' }),
      breedRepository.create({ name: 'Barbet', size: Size.Medium, uid: '64' }),
      breedRepository.create({ name: 'Basenji', size: Size.Small, uid: '65' }),
      breedRepository.create({ name: 'Basque Shepherd Dog', size: Size.Large, uid: '66 - A' }),
      breedRepository.create({ name: 'Basset Artesien Normand', size: Size.Medium, uid: '67' }),
      breedRepository.create({ name: 'Basset Bleu de Gascogne', size: Size.Medium, uid: '68 - A' }),
      breedRepository.create({
        name: 'Basset Fauve de Bretagne',
        size: Size.Medium,
        uid: '71 - A',
      }),
      breedRepository.create({ name: 'Basset Hound', size: Size.Medium, uid: '72' }),
      breedRepository.create({ name: 'Bavarian Mountain Hound', size: Size.Medium, uid: '73 - B' }),
      breedRepository.create({
        name: 'Bavarian Mountain Scent Hound',
        size: Size.Medium,
        uid: '73 - A',
      }),
      breedRepository.create({ name: 'Beagle ', size: Size.Small, uid: '74' }),
      breedRepository.create({ name: 'Beagle Harrier', size: Size.Medium, uid: '75' }),
      breedRepository.create({ name: 'Beagle-Chi', size: Size.Small, uid: '9953 - B' }),
      breedRepository.create({ name: 'Beaglier', size: Size.Small, uid: '9943' }),
      breedRepository.create({ name: 'Bearded Collie', size: Size.Medium, uid: '76' }),
      breedRepository.create({ name: 'Beauce Sheep Dog', size: Size.Large, uid: '77 - C' }),
      breedRepository.create({ name: 'Beauceron', size: Size.Large, uid: '77 - A' }),
      breedRepository.create({ name: 'Bedlington Terrier', size: Size.Small, uid: '78' }),
      breedRepository.create({
        name: 'Belgian Shepherd (Groenendael)',
        size: Size.Medium,
        uid: '79',
      }),
      breedRepository.create({
        name: 'Belgian Shepherd (Laekenois)',
        size: Size.Medium,
        uid: '80',
      }),
      breedRepository.create({ name: 'Belgian Shepherd (Malinois)', size: Size.Large, uid: '81' }),
      breedRepository.create({ name: 'Belgian Shepherd (Tervuren)', size: Size.Large, uid: '82' }),
      breedRepository.create({ name: 'Bergamasco Sheepdog', size: Size.Large, uid: '83' }),
      breedRepository.create({ name: 'Berger Blanc Suisse', size: Size.Large, uid: '84 - A' }),
      breedRepository.create({ name: 'Berger de Beauce', size: Size.Large, uid: '77 - B' }),
      breedRepository.create({ name: 'Berger de Brie', size: Size.Large, uid: '122 - B' }),
      breedRepository.create({ name: 'Berger des Pyrenees', size: Size.Small, uid: '417 - B' }),
      breedRepository.create({ name: 'Berger Picard', size: Size.Medium, uid: '85 - A' }),
      breedRepository.create({ name: 'Bernedoodle (Toy / Tiny)', size: Size.Small, uid: '9944' }),
      breedRepository.create({ name: 'Bernedoodle (Miniature)', size: Size.Medium, uid: '9945' }),
      breedRepository.create({ name: 'Bernedoodle (Standard)', size: Size.Large, uid: '9946' }),
      breedRepository.create({
        name: 'Berner Laufhund (Schweizer Laufhund)',
        size: Size.Medium,
        uid: '86 - A',
      }),
      breedRepository.create({
        name: 'Berner Niederlaufhund (Schweizer Niederlaufhund)',
        size: Size.Small,
        uid: '90 - A',
      }),
      breedRepository.create({
        name: 'Bernese Hound (Swiss Hound)',
        size: Size.Medium,
        uid: '86 - B',
      }),
      breedRepository.create({ name: 'Bernese Mountain Dog', size: Size.Large, uid: '94' }),
      breedRepository.create({ name: 'Bichon Frise', size: Size.Small, uid: '95' }),
      breedRepository.create({ name: 'Bichon Poo', size: Size.Small, uid: '9983 - C' }),
      breedRepository.create({ name: 'Bichpoo', size: Size.Small, uid: '9983 - B' }),
      breedRepository.create({ name: 'Biewer Terrier', size: Size.Small, uid: '96' }),
      breedRepository.create({ name: 'Billy', size: Size.Large, uid: '97' }),
      breedRepository.create({ name: 'Black and Tan Coonhound', size: Size.Large, uid: '98' }),
      breedRepository.create({ name: 'Black Forest Hound', size: Size.Medium, uid: '473 - C' }),
      breedRepository.create({ name: 'Black Mouth Cur', size: Size.Medium, uid: '99' }),
      breedRepository.create({ name: 'Black Russian Terrier', size: Size.Large, uid: '100' }),
      breedRepository.create({ name: 'Bloodhound', size: Size.Large, uid: '101' }),
      breedRepository.create({ name: 'Blue Gascony Basset', size: Size.Medium, uid: '68 - B' }),
      breedRepository.create({ name: 'Blue Gascony Griffon', size: Size.Medium, uid: '260 - B' }),
      breedRepository.create({ name: 'Blue Heeler', size: Size.Medium, uid: '48 - C' }),
      breedRepository.create({ name: 'Blue Lacy', size: Size.Medium, uid: '102' }),
      breedRepository.create({ name: 'Blue Picardy Spaniel', size: Size.Medium, uid: '103 - A' }),
      breedRepository.create({ name: 'Bluetick Coonhound', size: Size.Large, uid: '104' }),
      breedRepository.create({ name: 'Boerboel', size: Size.Large, uid: '105' }),
      breedRepository.create({ name: 'Bohemian Shepherd', size: Size.Medium, uid: '106' }),
      breedRepository.create({ name: 'Bohemian Spotted Dog', size: Size.Medium, uid: '156 - B' }),
      breedRepository.create({
        name: 'Bohemian Wirehaired Pointing Griffon',
        size: Size.Large,
        uid: '155 - B',
      }),
      breedRepository.create({ name: 'Bolognese', size: Size.Small, uid: '107' }),
      breedRepository.create({ name: 'Borador', size: Size.Medium, uid: '9947' }),
      breedRepository.create({ name: 'Border Collie', size: Size.Medium, uid: '108' }),
      breedRepository.create({ name: 'Border Terrier', size: Size.Small, uid: '109' }),
      breedRepository.create({ name: 'Borzoi', size: Size.Large, uid: '110 - A' }),
      breedRepository.create({
        name: 'Bosnian and Herzegovinian Croatian Shepherd Dog',
        size: Size.Large,
        uid: '501 - B',
      }),
      breedRepository.create({
        name: 'Bosnian Broken Haired Hound',
        size: Size.Medium,
        uid: '62 - B',
      }),
      breedRepository.create({
        name: 'Bosnian Coarse Haired Hound',
        size: Size.Medium,
        uid: '62 - C',
      }),
      breedRepository.create({ name: 'Boston Terrier', size: Size.Small, uid: '111' }),
      breedRepository.create({ name: 'Bourbonnais Pointer', size: Size.Medium, uid: '117 - B' }),
      breedRepository.create({ name: 'Bouvier des Ardennes', size: Size.Large, uid: '112' }),
      breedRepository.create({ name: 'Bouvier des Flandres', size: Size.Large, uid: '113' }),
      breedRepository.create({ name: 'Boxer', size: Size.Large, uid: '114' }),
      breedRepository.create({ name: 'Boykin Spaniel', size: Size.Medium, uid: '115' }),
      breedRepository.create({ name: 'Bracco Italiano', size: Size.Large, uid: '116 - A' }),
      breedRepository.create({ name: "Braque d'Auvergne", size: Size.Medium, uid: '57 - B' }),
      breedRepository.create({ name: "Braque de l'Ariege", size: Size.Large, uid: '43 - B' }),
      breedRepository.create({ name: 'Braque du Bourbonnais', size: Size.Medium, uid: '117 - A' }),
      breedRepository.create({
        name: 'Braque Francais (Gascogne)',
        size: Size.Large,
        uid: '118 - A',
      }),
      breedRepository.create({
        name: 'Braque Francais (Pyrenean)',
        size: Size.Medium,
        uid: '119 - A',
      }),
      breedRepository.create({
        name: 'Braque Francais de Grande Taille',
        size: Size.Large,
        uid: '118 - C',
      }),
      breedRepository.create({
        name: 'Braque Francais de Petite Taille',
        size: Size.Medium,
        uid: '119 - C',
      }),
      breedRepository.create({ name: 'Braque Saint Germain', size: Size.Medium, uid: '120 - A' }),
      breedRepository.create({ name: 'Brazilian Terrier', size: Size.Small, uid: '121' }),
      breedRepository.create({ name: 'Briard', size: Size.Large, uid: '122 - A' }),
      breedRepository.create({ name: 'Briquet Griffon Vendeen', size: Size.Medium, uid: '252' }),
      breedRepository.create({ name: 'Brittany', size: Size.Medium, uid: '123' }),
      breedRepository.create({ name: 'Broholmer', size: Size.Large, uid: '124 - A' }),
      breedRepository.create({ name: 'Brussels Griffon', size: Size.Small, uid: '125 - A' }),
      breedRepository.create({ name: 'Bucovina Shepherd Dog', size: Size.Large, uid: '126' }),
      breedRepository.create({
        name: 'Bulgarian Hound (Balgarski Barak)',
        size: Size.Medium,
        uid: '127',
      }),
      breedRepository.create({
        name: 'Bulgarian Scenthound (Balgarsko Gonche)',
        size: Size.Medium,
        uid: '128',
      }),
      breedRepository.create({ name: 'Bulgarian Shepherd Dog', size: Size.Large, uid: '295 - B' }),
      breedRepository.create({ name: 'Bull Terrier', size: Size.Medium, uid: '130' }),
      breedRepository.create({ name: 'Bull Terrier (Miniature)', size: Size.Small, uid: '129' }),
      breedRepository.create({ name: 'Bullmastiff', size: Size.Large, uid: '131' }),
      breedRepository.create({
        name: 'Bullpug (Miniature Bulldog)',
        size: Size.Medium,
        uid: '9948',
      }),
      breedRepository.create({ name: 'Bully Kutta', size: Size.Large, uid: '132' }),
      breedRepository.create({ name: 'Burgos Pointer', size: Size.Large, uid: '133 - A' }),
      breedRepository.create({ name: 'Ca de Bestiar', size: Size.Large, uid: '334 - B' }),
      breedRepository.create({ name: 'Ca de Bou', size: Size.Large, uid: '134 - A' }),
      breedRepository.create({ name: 'Ca Me Mallorqui', size: Size.Medium, uid: '135' }),
      breedRepository.create({ name: 'Ca Rater Mallorqui', size: Size.Small, uid: '333 - B' }),
      breedRepository.create({ name: 'Cairn Terrier', size: Size.Small, uid: '136' }),
      breedRepository.create({ name: 'Calupoh', size: Size.Large, uid: '137' }),
      breedRepository.create({ name: 'Campeiro Bulldog', size: Size.Large, uid: '138' }),
      breedRepository.create({ name: 'Can de Palleiro', size: Size.Large, uid: '139' }),
      breedRepository.create({ name: 'Canaan Dog', size: Size.Medium, uid: '140' }),
      breedRepository.create({ name: 'Canadian Eskimo Dog', size: Size.Large, uid: '141 - A' }),
      breedRepository.create({ name: 'Canadian Inuit Dog', size: Size.Large, uid: '141 - B' }),
      breedRepository.create({ name: 'Canarian Warren Hound', size: Size.Medium, uid: '388 - B' }),
      breedRepository.create({ name: 'Cane Corso', size: Size.Large, uid: '142' }),
      breedRepository.create({ name: 'Cane di Oropa', size: Size.Large, uid: '143' }),
      breedRepository.create({ name: 'Cantabrian Water Dog', size: Size.Medium, uid: '144' }),
      breedRepository.create({ name: 'Cao da Serra da Estrela', size: Size.Large, uid: '213 - B' }),
      breedRepository.create({ name: 'Cao de Castro Laboreiro', size: Size.Large, uid: '145 - A' }),
      breedRepository.create({
        name: 'Cao de Gado Transmontano',
        size: Size.Large,
        uid: '146 - A',
      }),
      breedRepository.create({ name: 'Cao Fila de Sao Miguel', size: Size.Large, uid: '438' }),
      breedRepository.create({ name: 'Carea Leones', size: Size.Medium, uid: '147 - A' }),
      breedRepository.create({ name: 'Carolina Dog', size: Size.Medium, uid: '148' }),
      breedRepository.create({ name: 'Castro Laboreiro Dog', size: Size.Large, uid: '145 - C' }),
      breedRepository.create({ name: 'Catahoula Bulldog', size: Size.Large, uid: '149' }),
      breedRepository.create({ name: 'Catahoula Leopard Dog', size: Size.Large, uid: '150' }),
      breedRepository.create({ name: 'Catalan Sheepdog', size: Size.Medium, uid: '151 - A' }),
      breedRepository.create({ name: 'Catalonian Sheepdog', size: Size.Medium, uid: '151 - B' }),
      breedRepository.create({ name: 'Caucasian Mountain Dog', size: Size.Large, uid: '152 - C' }),
      breedRepository.create({ name: 'Caucasian Ovcharka', size: Size.Large, uid: '152 - B' }),
      breedRepository.create({ name: 'Caucasian Shepherd Dog ', size: Size.Large, uid: '152 - A' }),
      breedRepository.create({ name: 'Cava-Lon', size: Size.Small, uid: '9949' }),
      breedRepository.create({ name: 'Cavachon', size: Size.Small, uid: '9950' }),
      breedRepository.create({ name: 'Cavadoodle', size: Size.Small, uid: '9952 - B' }),
      breedRepository.create({ name: 'Cavador', size: Size.Medium, uid: '9951' }),
      breedRepository.create({
        name: 'Cavalier King Charles Spaniel',
        size: Size.Small,
        uid: '153',
      }),
      breedRepository.create({ name: 'Cavapoo', size: Size.Small, uid: '9952 - A' }),
      breedRepository.create({ name: 'Cavipoo', size: Size.Small, uid: '9952 - D' }),
      breedRepository.create({ name: 'Cavoodle', size: Size.Small, uid: '9952 - C' }),
      breedRepository.create({ name: 'Central Asian Shepherd Dog', size: Size.Large, uid: '154' }),
      breedRepository.create({ name: 'Cesky Fousek', size: Size.Large, uid: '155 - A' }),
      breedRepository.create({ name: 'Cesky Strakaty Pes', size: Size.Medium, uid: '156 - A' }),
      breedRepository.create({ name: 'Cesky Terrier', size: Size.Small, uid: '157' }),
      breedRepository.create({ name: 'Cheagle', size: Size.Small, uid: '9953 - A' }),
      breedRepository.create({ name: 'Chesapeake Bay Retriever', size: Size.Large, uid: '158' }),
      breedRepository.create({ name: 'Chi-Pom', size: Size.Small, uid: '9981 - C' }),
      breedRepository.create({ name: "Chien d'Artois", size: Size.Large, uid: '47 - B' }),
      breedRepository.create({ name: 'Chien de Franche-Comte', size: Size.Medium, uid: '401 - B' }),
      breedRepository.create({ name: 'Chihuahua', size: Size.Small, uid: '159' }),
      breedRepository.create({ name: 'Chilean Fox Terrier', size: Size.Small, uid: '160 - A' }),
      breedRepository.create({ name: 'Chilean Terrier', size: Size.Small, uid: '160 - B' }),
      breedRepository.create({ name: 'Chimeranian', size: Size.Small, uid: '9981 - B' }),
      breedRepository.create({ name: 'Chinese Crested Dog', size: Size.Small, uid: '161' }),
      breedRepository.create({
        name: 'Chinese Imperial Dog (Imperial Shih Tzu)',
        size: Size.Small,
        uid: '162',
      }),
      breedRepository.create({ name: 'Chinook', size: Size.Large, uid: '163' }),
      breedRepository.create({ name: 'Chion', size: Size.Small, uid: '9954 - A' }),
      breedRepository.create({ name: 'Chipin', size: Size.Small, uid: '9955' }),
      breedRepository.create({ name: 'Chippiparai', size: Size.Medium, uid: '164' }),
      breedRepository.create({ name: 'Chiweenie', size: Size.Small, uid: '9956' }),
      breedRepository.create({ name: 'Chongqing Dog', size: Size.Medium, uid: '165' }),
      breedRepository.create({ name: 'Chorkie', size: Size.Small, uid: '9957 - A' }),
      breedRepository.create({ name: 'Chortai', size: Size.Large, uid: '166 - A' }),
      breedRepository.create({ name: 'Chow Chow', size: Size.Large, uid: '167' }),
      breedRepository.create({ name: 'Chuandong Hound', size: Size.Medium, uid: '168' }),
      breedRepository.create({ name: 'Chug', size: Size.Small, uid: '9958' }),
      breedRepository.create({ name: 'Cimarron Uruguayo', size: Size.Large, uid: '169' }),
      breedRepository.create({ name: "Cirneco dell'Etna", size: Size.Small, uid: '170' }),
      breedRepository.create({ name: 'Clumber Spaniel', size: Size.Large, uid: '171' }),
      breedRepository.create({ name: 'Cockalier', size: Size.Small, uid: '9959' }),
      breedRepository.create({ name: 'Cockapoo (Toy / Miniature)', size: Size.Small, uid: '9960' }),
      breedRepository.create({ name: 'Cockapoo (Maxi)', size: Size.Medium, uid: '9961' }),
      breedRepository.create({ name: 'Collie (Rough)', size: Size.Large, uid: '172' }),
      breedRepository.create({ name: 'Collie (Smooth)', size: Size.Large, uid: '173' }),
      breedRepository.create({
        name: 'Colombian Fino Hound (Grande / Large)',
        size: Size.Large,
        uid: '175',
      }),
      breedRepository.create({
        name: 'Colombian Fino Hound (Standard)',
        size: Size.Medium,
        uid: '174',
      }),
      breedRepository.create({ name: 'Continental Bulldog', size: Size.Large, uid: '176' }),
      breedRepository.create({ name: 'Continental Toy Spaniel', size: Size.Small, uid: '370 - B' }),
      breedRepository.create({ name: 'Corgidor', size: Size.Medium, uid: '9962' }),
      breedRepository.create({ name: 'Coton de Tulear', size: Size.Small, uid: '177' }),
      breedRepository.create({ name: 'Cretan Hound', size: Size.Medium, uid: '178' }),
      breedRepository.create({ name: 'Croatian Sheepdog', size: Size.Medium, uid: '179' }),
      breedRepository.create({ name: 'Curly-Coated Retriever', size: Size.Large, uid: '180' }),
      breedRepository.create({ name: 'Czech Spotted Dog', size: Size.Medium, uid: '156 - C' }),
      breedRepository.create({ name: 'Czechoslovakian Vlcak', size: Size.Large, uid: '181 - B' }),
      breedRepository.create({ name: 'Czechoslovakian Wolfdog', size: Size.Large, uid: '181 - A' }),
      breedRepository.create({ name: 'Dachshund', size: Size.Small, uid: '182' }),
      breedRepository.create({ name: 'Dalmatian', size: Size.Large, uid: '183' }),
      breedRepository.create({ name: 'Dandie Dinmont Terrier', size: Size.Small, uid: '184' }),
      breedRepository.create({ name: 'Danish Mastiff', size: Size.Large, uid: '124 - B' }),
      breedRepository.create({ name: 'Danish Spitz', size: Size.Medium, uid: '185' }),
      breedRepository.create({ name: 'Danish-Swedish Farmdog', size: Size.Small, uid: '186' }),
      breedRepository.create({ name: 'Deutsch Drahthaar', size: Size.Large, uid: '235 - B' }),
      breedRepository.create({ name: 'Deutsch Kurzhaar', size: Size.Large, uid: '234 - B' }),
      breedRepository.create({ name: 'Deutsch Langhaar', size: Size.Large, uid: '232 - B' }),
      breedRepository.create({ name: 'Deutsch Stichelhaar', size: Size.Large, uid: '233 - B' }),
      breedRepository.create({
        name: 'Deutsche Bracke (German Hound)',
        size: Size.Medium,
        uid: '187',
      }),
      breedRepository.create({
        name: 'Deutscher Wachtelhund (German Spaniel)',
        size: Size.Medium,
        uid: '188',
      }),
      breedRepository.create({ name: 'Doberman Pinscher', size: Size.Large, uid: '189 - A' }),
      breedRepository.create({ name: 'Dobermann', size: Size.Large, uid: '189 - B' }),
      breedRepository.create({ name: 'Dogo Argentino', size: Size.Large, uid: '190' }),
      breedRepository.create({ name: 'Dogo Guatemalteco', size: Size.Large, uid: '191 - A' }),
      breedRepository.create({ name: 'Dogue Brasileiro', size: Size.Large, uid: '192' }),
      breedRepository.create({ name: 'Dogue de Bordeaux', size: Size.Large, uid: '193' }),
      breedRepository.create({ name: 'Donggyeongi (Daeng Gyeon)', size: Size.Medium, uid: '194' }),
      breedRepository.create({ name: 'Doxiepoo', size: Size.Small, uid: '9963' }),
      breedRepository.create({ name: 'Drentsche Patrijshond', size: Size.Large, uid: '195 - A' }),
      breedRepository.create({ name: 'Drever', size: Size.Medium, uid: '196' }),
      breedRepository.create({ name: 'Dunker (Norwegian Hound)', size: Size.Medium, uid: '197' }),
      breedRepository.create({ name: 'Dutch Partridge Dog', size: Size.Large, uid: '195 - B' }),
      breedRepository.create({ name: 'Dutch Shepherd', size: Size.Large, uid: '198' }),
      breedRepository.create({ name: 'Dutch Smoushond', size: Size.Small, uid: '199' }),
      breedRepository.create({ name: 'Dutch Tulip Hound', size: Size.Small, uid: '338 - B' }),
      breedRepository.create({ name: 'Dwarf Spitz', size: Size.Small, uid: '242 - B' }),
      breedRepository.create({ name: 'East European Shepherd', size: Size.Large, uid: '200' }),
      breedRepository.create({ name: 'East Siberian Laika', size: Size.Medium, uid: '201' }),
      breedRepository.create({ name: 'Eesti Hagijas', size: Size.Medium, uid: '212 - B' }),
      breedRepository.create({ name: 'English Bulldog', size: Size.Medium, uid: '202' }),
      breedRepository.create({ name: 'English Cocker Spaniel', size: Size.Medium, uid: '25' }),
      breedRepository.create({ name: 'English Coonhound', size: Size.Large, uid: '26 - C' }),
      breedRepository.create({ name: 'English Foxhound', size: Size.Large, uid: '204' }),
      breedRepository.create({ name: 'English Mastiff', size: Size.Large, uid: '205 - A' }),
      breedRepository.create({ name: 'English Setter', size: Size.Large, uid: '206' }),
      breedRepository.create({ name: 'English Shepherd', size: Size.Medium, uid: '207' }),
      breedRepository.create({ name: 'English Springer Spaniel', size: Size.Medium, uid: '208' }),
      breedRepository.create({ name: 'English Toy Spaniel', size: Size.Small, uid: '209 - A' }),
      breedRepository.create({
        name: 'English Toy Terrier (Black and Tan)',
        size: Size.Small,
        uid: '210',
      }),
      breedRepository.create({ name: 'Entelbucher Cattle Dog', size: Size.Medium, uid: '211 - B' }),
      breedRepository.create({
        name: 'Entlebucher Mountain Dog',
        size: Size.Medium,
        uid: '211 - A',
      }),
      breedRepository.create({
        name: 'Epagneul Bleu de Picardie',
        size: Size.Medium,
        uid: '103 - B',
      }),
      breedRepository.create({
        name: 'Epagneul de Saint-Usuge',
        size: Size.Medium,
        uid: '439 - B',
      }),
      breedRepository.create({ name: 'Epagneul Pont-Audemer', size: Size.Medium, uid: '397 - B' }),
      breedRepository.create({ name: 'Estonian Hound', size: Size.Medium, uid: '212 - A' }),
      breedRepository.create({ name: 'Estrela Mountain Dog', size: Size.Large, uid: '213 - A' }),
      breedRepository.create({ name: 'Eurasier', size: Size.Medium, uid: '214' }),
      breedRepository.create({ name: 'Euskal Artzain Txakurra ', size: Size.Large, uid: '66 - C' }),
      breedRepository.create({ name: 'Fawn Brittany Basset', size: Size.Medium, uid: '71 - B' }),
      breedRepository.create({ name: 'Fawn Brittany Griffon', size: Size.Medium, uid: '261 - B' }),
      breedRepository.create({ name: 'Field Spaniel', size: Size.Medium, uid: '215' }),
      breedRepository.create({
        name: 'Fila Brasileiro (Brazilian Mastiff)',
        size: Size.Large,
        uid: '216',
      }),
      breedRepository.create({ name: 'Finnish Hound', size: Size.Medium, uid: '217 - A' }),
      breedRepository.create({ name: 'Finnish Lapphund', size: Size.Medium, uid: '218 - A' }),
      breedRepository.create({ name: 'Finnish Spitz', size: Size.Small, uid: '219' }),
      breedRepository.create({ name: 'Flat Coated Retriever', size: Size.Large, uid: '220' }),
      breedRepository.create({ name: 'Formosan Mountain Dog', size: Size.Medium, uid: '221 - A' }),
      breedRepository.create({ name: 'Francais Blanc et Noir', size: Size.Large, uid: '222 - A' }),
      breedRepository.create({
        name: 'Francais Blanc et Orange',
        size: Size.Large,
        uid: '223 - A',
      }),
      breedRepository.create({ name: 'Francais Tricolore', size: Size.Large, uid: '224 - A' }),
      breedRepository.create({ name: 'French Bulldog', size: Size.Small, uid: '225' }),
      breedRepository.create({
        name: 'French Pointing Dog (Gascogne)',
        size: Size.Large,
        uid: '118 - B',
      }),
      breedRepository.create({
        name: 'French Pointing Dog (Pyrenean)',
        size: Size.Medium,
        uid: '119 - B',
      }),
      breedRepository.create({
        name: 'French Spaniel (Epagneul Francais)',
        size: Size.Medium,
        uid: '226',
      }),
      breedRepository.create({ name: 'French Tricolour Hound', size: Size.Large, uid: '224 - B' }),
      breedRepository.create({
        name: 'French White and Black Hound',
        size: Size.Large,
        uid: '222 - B',
      }),
      breedRepository.create({
        name: 'French White and Orange Hound',
        size: Size.Large,
        uid: '223 - B',
      }),
      breedRepository.create({ name: 'Frisian Water Dog', size: Size.Large, uid: '524 - B' }),
      breedRepository.create({
        name: 'Galgo Espanol (Spanish Greyhound)',
        size: Size.Large,
        uid: '227',
      }),
      breedRepository.create({ name: 'Gascon Saintongeois (Grand)', size: Size.Large, uid: '229' }),
      breedRepository.create({
        name: 'Gascon Saintongeois (Petit)',
        size: Size.Medium,
        uid: '228',
      }),
      breedRepository.create({ name: 'Gaucho Sheepdog', size: Size.Large, uid: '230 - A' }),
      breedRepository.create({ name: 'Georgian Shepherd', size: Size.Large, uid: '231' }),
      breedRepository.create({
        name: 'German Longhaired Pointer',
        size: Size.Large,
        uid: '232 - A',
      }),
      breedRepository.create({ name: 'German Pinscher', size: Size.Medium, uid: '236' }),
      breedRepository.create({
        name: 'German Rough Haired Pointer',
        size: Size.Large,
        uid: '233 - A',
      }),
      breedRepository.create({ name: 'German Shepherd (Alsatian)', size: Size.Large, uid: '237' }),
      breedRepository.create({
        name: 'German Shorthaired Pointer',
        size: Size.Large,
        uid: '234 - A',
      }),
      breedRepository.create({
        name: 'German Spitz (Toy / Miniature)',
        size: Size.Small,
        uid: '238 - A',
      }),
      breedRepository.create({ name: 'German Spitz (Medium)', size: Size.Small, uid: '239 - A' }),
      breedRepository.create({
        name: 'German Spitz (Giant / Large)',
        size: Size.Medium,
        uid: '240 - A',
      }),
      breedRepository.create({
        name: 'German Wirehaired Pointer',
        size: Size.Large,
        uid: '235 - A',
      }),
      breedRepository.create({ name: 'Glen of Imaal Terrier', size: Size.Medium, uid: '243' }),
      breedRepository.create({ name: 'Goldador', size: Size.Large, uid: '9964' }),
      breedRepository.create({ name: 'Golden Retriever', size: Size.Large, uid: '244' }),
      breedRepository.create({
        name: 'Goldendoodle (Toy / Miniature)',
        size: Size.Small,
        uid: '9965',
      }),
      breedRepository.create({ name: 'Goldendoodle (Standard)', size: Size.Large, uid: '9966' }),
      breedRepository.create({ name: 'Gordon Setter', size: Size.Large, uid: '245' }),
      breedRepository.create({ name: 'Gos Rater Valencia', size: Size.Small, uid: '510' }),
      breedRepository.create({ name: 'Gran Mastin de Borinquen', size: Size.Large, uid: '246' }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Blanc et Noir',
        size: Size.Large,
        uid: '247 - A',
      }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Blanc et Orange',
        size: Size.Large,
        uid: '248 - A',
      }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Tricolore',
        size: Size.Large,
        uid: '249 - A',
      }),
      breedRepository.create({
        name: 'Grand Basset Griffon Vendeen',
        size: Size.Medium,
        uid: '251',
      }),
      breedRepository.create({ name: 'Grand Bleu de Gascogne', size: Size.Large, uid: '70 - A' }),
      breedRepository.create({
        name: 'Great Anglo-French Tricolour Hound',
        size: Size.Large,
        uid: '249 - B',
      }),
      breedRepository.create({
        name: 'Great Anglo-French White and Black Hound',
        size: Size.Large,
        uid: '247 - B',
      }),
      breedRepository.create({
        name: 'Great Anglo-French White and Orange Hound',
        size: Size.Large,
        uid: '248 - B',
      }),
      breedRepository.create({ name: 'Great Dane', size: Size.Large, uid: '253' }),
      breedRepository.create({ name: 'Great Gascony Blue', size: Size.Large, uid: '70 - B' }),
      breedRepository.create({ name: 'Great Pyrenees', size: Size.Large, uid: '254 - A' }),
      breedRepository.create({ name: 'Greater Swiss Mountain Dog', size: Size.Large, uid: '255' }),
      breedRepository.create({ name: 'Greek Harehound', size: Size.Medium, uid: '256 - A' }),
      breedRepository.create({ name: 'Greek Shepherd', size: Size.Large, uid: '257' }),
      breedRepository.create({ name: 'Greenland Dog', size: Size.Large, uid: '258' }),
      breedRepository.create({ name: 'Greyhound', size: Size.Large, uid: '259' }),
      breedRepository.create({
        name: 'Griffon Bleu de Gascogne',
        size: Size.Medium,
        uid: '260 - A',
      }),
      breedRepository.create({ name: 'Griffon Bruxellois', size: Size.Small, uid: '125 - B' }),
      breedRepository.create({
        name: 'Griffon Fauve de Bretagne',
        size: Size.Medium,
        uid: '261 - A',
      }),
      breedRepository.create({ name: 'Griffon Nivernais', size: Size.Medium, uid: '262' }),
      breedRepository.create({
        name: 'Großspitz (Gross Spitz)',
        size: Size.Medium,
        uid: '240 - B',
      }),
      breedRepository.create({ name: 'Guatemalan Dogo', size: Size.Large, uid: '191 - B' }),
      breedRepository.create({ name: 'Gull Dong', size: Size.Large, uid: '263' }),
      breedRepository.create({ name: 'Halden Hound', size: Size.Medium, uid: '264 - A' }),
      breedRepository.create({ name: 'Haldenstover', size: Size.Medium, uid: '264 - B' }),
      breedRepository.create({ name: 'Hamilton Hound', size: Size.Large, uid: '265 - B' }),
      breedRepository.create({ name: 'Hamiltonstovare', size: Size.Large, uid: '265 - A' }),
      breedRepository.create({
        name: 'Hannoverscher Schweisshund',
        size: Size.Large,
        uid: '266 - C',
      }),
      breedRepository.create({ name: 'Hanoverian Hound', size: Size.Large, uid: '266 - B' }),
      breedRepository.create({ name: 'Hanoverian Scenthound', size: Size.Large, uid: '266 - A' }),
      breedRepository.create({ name: 'Harrier', size: Size.Medium, uid: '267' }),
      breedRepository.create({ name: 'Havanese', size: Size.Small, uid: '268' }),
      breedRepository.create({ name: 'Hellenic Hound', size: Size.Medium, uid: '256 - B' }),
      breedRepository.create({ name: 'Hellinikos Ichnilatis', size: Size.Medium, uid: '256 - C' }),
      breedRepository.create({ name: 'Hierran Wolfdog', size: Size.Medium, uid: '323 - C' }),
      breedRepository.create({ name: 'Himalayan Sheepdog', size: Size.Large, uid: '269' }),
      breedRepository.create({ name: 'Hmong Bobtail Dog', size: Size.Medium, uid: '270 - A' }),
      breedRepository.create({ name: 'Hmong Docked Tail Dog', size: Size.Medium, uid: '270 - B' }),
      breedRepository.create({ name: 'Hokkaido', size: Size.Medium, uid: '271' }),
      breedRepository.create({ name: 'Hortaya Borzaya', size: Size.Large, uid: '166 - B' }),
      breedRepository.create({ name: 'Hovawart', size: Size.Large, uid: '272' }),
      breedRepository.create({
        name: 'Hungarian Greyhound (Magyar Agar) ',
        size: Size.Large,
        uid: '331',
      }),
      breedRepository.create({ name: 'Hushan Dog', size: Size.Medium, uid: '322 - B' }),
      breedRepository.create({ name: 'Huskador', size: Size.Medium, uid: '9973 - B' }),
      breedRepository.create({ name: 'Hygenhund (Hygen Hound)', size: Size.Medium, uid: '273' }),
      breedRepository.create({ name: 'Ibizan Hound', size: Size.Medium, uid: '274 - A' }),
      breedRepository.create({ name: 'Ibizan Podenco', size: Size.Medium, uid: '274 - C' }),
      breedRepository.create({ name: 'Icelandic Sheepdog', size: Size.Medium, uid: '275' }),
      breedRepository.create({
        name: 'Indian Spitz (Smaller / Lesser)',
        size: Size.Small,
        uid: '276',
      }),
      breedRepository.create({ name: 'Indian Spitz (Greater)', size: Size.Medium, uid: '277' }),
      breedRepository.create({ name: 'Irish Doodle (Miniature)', size: Size.Medium, uid: '9967' }),
      breedRepository.create({ name: 'Irish Doodle (Standard)', size: Size.Large, uid: '9968' }),
      breedRepository.create({ name: 'Irish Red and White Setter', size: Size.Medium, uid: '278' }),
      breedRepository.create({ name: 'Irish Setter', size: Size.Large, uid: '279' }),
      breedRepository.create({ name: 'Irish Terrier', size: Size.Medium, uid: '280' }),
      breedRepository.create({ name: 'Irish Water Spaniel', size: Size.Medium, uid: '281' }),
      breedRepository.create({ name: 'Irish Wolfhound', size: Size.Large, uid: '282' }),
      breedRepository.create({
        name: 'Istrian Coarse Haired Hound',
        size: Size.Medium,
        uid: '283 - A',
      }),
      breedRepository.create({ name: 'Istrian Short Haired Hound', size: Size.Medium, uid: '284' }),
      breedRepository.create({
        name: 'Istrian Wirehaired Hound',
        size: Size.Medium,
        uid: '283 - B',
      }),
      breedRepository.create({ name: 'Italian Greyhound', size: Size.Small, uid: '285' }),
      breedRepository.create({ name: 'Italian Pointer', size: Size.Large, uid: '116 - B' }),
      breedRepository.create({ name: 'Jack Russell Terrier', size: Size.Small, uid: '286' }),
      breedRepository.create({
        name: 'Jagdterrier (German Hunting Terrier)',
        size: Size.Small,
        uid: '287',
      }),
      breedRepository.create({ name: 'Jamthund (Swedish Elkhound)', size: Size.Large, uid: '288' }),
      breedRepository.create({ name: 'Japanese Chin', size: Size.Small, uid: '289 - A' }),
      breedRepository.create({ name: 'Japanese Mastiff', size: Size.Large, uid: '502 - B' }),
      breedRepository.create({ name: 'Japanese Spaniel', size: Size.Small, uid: '289 - B' }),
      breedRepository.create({ name: 'Japanese Spitz', size: Size.Small, uid: '290' }),
      breedRepository.create({ name: 'Japanese Terrier', size: Size.Small, uid: '291' }),
      breedRepository.create({
        name: 'Jura Hound (Swiss Hound)',
        size: Size.Medium,
        uid: '87 - B',
      }),
      breedRepository.create({
        name: 'Jura Laufhund (Schweizer Laufhund)',
        size: Size.Medium,
        uid: '87 - A',
      }),
      breedRepository.create({
        name: 'Jura Niederlaufhund (Schweizer Niederlaufhund)',
        size: Size.Small,
        uid: '91 - A',
      }),
      breedRepository.create({ name: 'Kai Ken', size: Size.Medium, uid: '292' }),
      breedRepository.create({ name: 'Kanni', size: Size.Medium, uid: '294' }),
      breedRepository.create({ name: 'Karakachan', size: Size.Large, uid: '295 - A' }),
      breedRepository.create({ name: 'Karelian Bear Dog', size: Size.Medium, uid: '296' }),
      breedRepository.create({ name: 'Karelo-Finnish Laika', size: Size.Small, uid: '297' }),
      breedRepository.create({ name: 'Karst Shepherd', size: Size.Large, uid: '298' }),
      breedRepository.create({ name: 'Keeshond', size: Size.Medium, uid: '241 - A' }),
      breedRepository.create({ name: 'Kerry Beagle', size: Size.Medium, uid: '299' }),
      breedRepository.create({ name: 'Kerry Blue Terrier', size: Size.Medium, uid: '300' }),
      breedRepository.create({ name: 'King Charles Spaniel', size: Size.Small, uid: '209 - B' }),
      breedRepository.create({ name: 'King Shepherd', size: Size.Large, uid: '301' }),
      breedRepository.create({ name: 'Kintamani-Bali Dog', size: Size.Medium, uid: '302' }),
      breedRepository.create({ name: 'Kishu Ken', size: Size.Medium, uid: '303' }),
      breedRepository.create({ name: 'Kleinspitz', size: Size.Small, uid: '238 - B' }),
      breedRepository.create({ name: 'Kokoni', size: Size.Small, uid: '304 - A' }),
      breedRepository.create({ name: 'Komondor', size: Size.Large, uid: '305' }),
      breedRepository.create({
        name: 'Korean Dosa Mastiff (Mee Kyun Dosa)',
        size: Size.Large,
        uid: '306',
      }),
      breedRepository.create({ name: 'Korean Jindo', size: Size.Medium, uid: '307' }),
      breedRepository.create({ name: 'Korean Phungsan', size: Size.Large, uid: '415 - C' }),
      breedRepository.create({ name: 'Korthals Griffon', size: Size.Medium, uid: '525 - B' }),
      breedRepository.create({ name: 'Kromfohrlander', size: Size.Small, uid: '308' }),
      breedRepository.create({ name: 'Kuchi', size: Size.Large, uid: '309 - A' }),
      breedRepository.create({ name: 'Kunming Wolfdog', size: Size.Large, uid: '310' }),
      breedRepository.create({ name: 'Kuvasz', size: Size.Large, uid: '311' }),
      breedRepository.create({ name: 'Kyi-Leo', size: Size.Small, uid: '9969' }),
      breedRepository.create({
        name: 'Labradoodle (Miniature)',
        size: Size.Small,
        uid: '9970 - A',
      }),
      breedRepository.create({ name: 'Labradoodle (Medium)', size: Size.Medium, uid: '9971 - A' }),
      breedRepository.create({ name: 'Labradoodle (Standard)', size: Size.Large, uid: '9972 - A' }),
      breedRepository.create({ name: 'Labrador Retriever', size: Size.Large, uid: '312' }),
      breedRepository.create({ name: 'Labsky', size: Size.Medium, uid: '9973 - A' }),
      breedRepository.create({ name: 'Lagotto Romagnolo', size: Size.Medium, uid: '313 - A' }),
      breedRepository.create({ name: 'Lakeland Terrier', size: Size.Small, uid: '314' }),
      breedRepository.create({ name: 'Lancashire Heeler', size: Size.Small, uid: '315' }),
      breedRepository.create({ name: 'Landseer', size: Size.Large, uid: '316' }),
      breedRepository.create({ name: 'Lapinporokoira', size: Size.Large, uid: '317 - B' }),
      breedRepository.create({ name: 'Lapponian Herder', size: Size.Large, uid: '317 - A' }),
      breedRepository.create({ name: 'Large Munsterlander', size: Size.Large, uid: '318' }),
      breedRepository.create({ name: 'Leonberger', size: Size.Large, uid: '320' }),
      breedRepository.create({ name: 'Leonese Sheepdog', size: Size.Medium, uid: '147 - B' }),
      breedRepository.create({ name: 'Lhasa Apso', size: Size.Small, uid: '321' }),
      breedRepository.create({ name: 'Liangshan Hound', size: Size.Medium, uid: '322 - A' }),
      breedRepository.create({ name: 'Lobito Herreno', size: Size.Medium, uid: '323 - A' }),
      breedRepository.create({
        name: 'Longhaired Whippet (Silken Windsprite)',
        size: Size.Small,
        uid: '324',
      }),
      breedRepository.create({ name: 'Lowchen ', size: Size.Small, uid: '326' }),
      breedRepository.create({ name: 'Lucas Terrier', size: Size.Small, uid: '327' }),
      breedRepository.create({
        name: 'Lucerne Hound (Swiss Hound)',
        size: Size.Medium,
        uid: '89 - B',
      }),
      breedRepository.create({
        name: 'Lupo Italiano (Italian Wolfdog)',
        size: Size.Large,
        uid: '329',
      }),
      breedRepository.create({
        name: 'Luzerner Laufhund (Schweizer Laufhund)',
        size: Size.Medium,
        uid: '89 - A',
      }),
      breedRepository.create({
        name: 'Luzerner Niederlaufhund (Schweizer Niederlaufhund)',
        size: Size.Small,
        uid: '93 - A',
      }),
      breedRepository.create({ name: 'Mackenzie River Husky', size: Size.Large, uid: '330' }),
      breedRepository.create({ name: 'Majestic Tree Hound', size: Size.Large, uid: '332' }),
      breedRepository.create({ name: 'Majorca Mastiff', size: Size.Large, uid: '134 - C' }),
      breedRepository.create({ name: 'Majorca Ratter', size: Size.Small, uid: '333 - A' }),
      breedRepository.create({ name: 'Majorca Shepherd Dog', size: Size.Large, uid: '334 - A' }),
      breedRepository.create({ name: 'Malshi', size: Size.Small, uid: '9974 - A' }),
      breedRepository.create({ name: 'Maltese', size: Size.Small, uid: '335' }),
      breedRepository.create({ name: 'Maltese Shih Tzu', size: Size.Small, uid: '9974 - B' }),
      breedRepository.create({ name: 'Maltipoo', size: Size.Small, uid: '9975' }),
      breedRepository.create({ name: 'Manchester Terrier', size: Size.Small, uid: '336' }),
      breedRepository.create({ name: 'Maremma Sheepdog', size: Size.Large, uid: '337 - A' }),
      breedRepository.create({
        name: 'Maremmano-Abruzzese Sheepdog',
        size: Size.Large,
        uid: '337 - B',
      }),
      breedRepository.create({ name: 'Markiesje', size: Size.Small, uid: '338 - A' }),
      breedRepository.create({ name: 'Mastiff', size: Size.Large, uid: '205 - B' }),
      breedRepository.create({ name: 'Mastin Espanol', size: Size.Large, uid: '480 - B' }),
      breedRepository.create({ name: 'McNab', size: Size.Medium, uid: '339' }),
      breedRepository.create({
        name: 'Medium Sized Anglo-French Hound',
        size: Size.Medium,
        uid: '37 - B',
      }),
      breedRepository.create({ name: 'Meliteo Kinidio', size: Size.Small, uid: '304 - C' }),
      breedRepository.create({
        name: 'Mexican Hairless Dog (Toy)',
        size: Size.Small,
        uid: '340 - A',
      }),
      breedRepository.create({
        name: 'Mexican Hairless Dog (Miniature)',
        size: Size.Small,
        uid: '341 - A',
      }),
      breedRepository.create({
        name: 'Mexican Hairless Dog (Standard)',
        size: Size.Medium,
        uid: '342 - A',
      }),
      breedRepository.create({ name: 'Mi-Ki (Miki)', size: Size.Small, uid: '9976' }),
      breedRepository.create({
        name: 'Miniature American Shepherd',
        size: Size.Small,
        uid: '51 - A',
      }),
      breedRepository.create({ name: 'Miniature Fox Terrier', size: Size.Small, uid: '475 - A' }),
      breedRepository.create({ name: 'Miniature Pinscher', size: Size.Small, uid: '343' }),
      breedRepository.create({ name: 'Mittelschnauzer', size: Size.Medium, uid: '449 - B' }),
      breedRepository.create({ name: 'Mittelspitz', size: Size.Small, uid: '239 - B' }),
      breedRepository.create({ name: 'Molossus of Epirus', size: Size.Large, uid: '344' }),
      breedRepository.create({ name: 'Mongrel (唐狗)', size: Size.Medium, uid: '9998 - A' }),
      breedRepository.create({ name: 'Montenegrin Mountain Hound', size: Size.Medium, uid: '345' }),
      breedRepository.create({ name: 'Morkie ', size: Size.Small, uid: '9977 - A' }),
      breedRepository.create({ name: 'Moscow Watchdog', size: Size.Large, uid: '346' }),
      breedRepository.create({ name: 'Mountain Cur', size: Size.Medium, uid: '347' }),
      breedRepository.create({ name: 'Mountain Feist', size: Size.Small, uid: '348 - A' }),
      breedRepository.create({ name: 'Mountain View Cur', size: Size.Medium, uid: '349' }),
      breedRepository.create({ name: 'Mucuchies', size: Size.Large, uid: '350' }),
      breedRepository.create({ name: 'Mudi', size: Size.Small, uid: '351' }),
      breedRepository.create({ name: 'Murcian Ratter', size: Size.Small, uid: '422 - B' }),
      breedRepository.create({ name: 'Mutt (唐狗)', size: Size.Medium, uid: '9998 - B' }),
      breedRepository.create({
        name: 'Neapolitan Mastiff (Mastino Napoletano)',
        size: Size.Large,
        uid: '352',
      }),
      breedRepository.create({ name: 'Nederlandse Kooikerhondje', size: Size.Small, uid: '353' }),
      breedRepository.create({ name: 'New Zealand Heading Dog', size: Size.Large, uid: '354' }),
      breedRepository.create({ name: 'New Zealand Huntaway', size: Size.Large, uid: '355' }),
      breedRepository.create({ name: 'Newfoundland', size: Size.Large, uid: '356' }),
      breedRepository.create({ name: 'Norfolk Terrier', size: Size.Small, uid: '357' }),
      breedRepository.create({
        name: 'Norrbottenspets (Norrbottenspitz)',
        size: Size.Small,
        uid: '358',
      }),
      breedRepository.create({ name: 'Northern Inuit Dog', size: Size.Large, uid: '359' }),
      breedRepository.create({ name: 'Norwegian Buhund', size: Size.Medium, uid: '360' }),
      breedRepository.create({ name: 'Norwegian Elkhound', size: Size.Medium, uid: '361' }),
      breedRepository.create({ name: 'Norwegian Lundehund', size: Size.Small, uid: '362' }),
      breedRepository.create({ name: 'Norwich Terrier', size: Size.Small, uid: '363' }),
      breedRepository.create({
        name: 'Nova Scotia Duck Tolling Retriever',
        size: Size.Medium,
        uid: '364',
      }),
      breedRepository.create({
        name: 'Nureongi (Korean Yellow Spitz)',
        size: Size.Medium,
        uid: '365',
      }),
      breedRepository.create({ name: 'Old Danish Pointer', size: Size.Large, uid: '366' }),
      breedRepository.create({ name: 'Old English Sheepdog', size: Size.Large, uid: '367' }),
      breedRepository.create({
        name: 'Olde English Bulldogge (Old English Bulldog)',
        size: Size.Large,
        uid: '203',
      }),
      breedRepository.create({ name: 'Otterhound', size: Size.Large, uid: '368' }),
      breedRepository.create({ name: 'Ovejero Magallanico', size: Size.Medium, uid: '373 - B' }),
      breedRepository.create({ name: 'Ovelheiro Gaucho', size: Size.Large, uid: '230 - B' }),
      breedRepository.create({ name: 'Owczarek Podhalanski', size: Size.Large, uid: '492 - B' }),
      breedRepository.create({ name: 'Pachon Navarro', size: Size.Medium, uid: '369' }),
      breedRepository.create({ name: 'Papihuahua', size: Size.Small, uid: '9954 - B' }),
      breedRepository.create({ name: 'Papillon', size: Size.Small, uid: '370 - A' }),
      breedRepository.create({ name: 'Papshund', size: Size.Small, uid: '9978' }),
      breedRepository.create({ name: 'Parson Russell Terrier', size: Size.Small, uid: '371' }),
      breedRepository.create({ name: 'Patagonian Sheepdog', size: Size.Medium, uid: '373 - A' }),
      breedRepository.create({ name: 'Patterdale Terrier', size: Size.Small, uid: '374' }),
      breedRepository.create({ name: 'Peekapoo', size: Size.Small, uid: '9979 - A' }),
      breedRepository.create({ name: 'Pekeapoo', size: Size.Small, uid: '9979 - B' }),
      breedRepository.create({ name: 'Pekepoo', size: Size.Small, uid: '9979 - C' }),
      breedRepository.create({ name: 'Pekingese', size: Size.Small, uid: '375' }),
      breedRepository.create({ name: 'Perdigueiro Galego', size: Size.Medium, uid: '376' }),
      breedRepository.create({ name: 'Perdiguero de Burgos', size: Size.Large, uid: '133 - C' }),
      breedRepository.create({ name: 'Perro de Agua Espanol', size: Size.Medium, uid: '481 - B' }),
      breedRepository.create({ name: 'Perro de Pastor Garafiano ', size: Size.Large, uid: '372' }),
      breedRepository.create({
        name: 'Perro de Pastor Herreno',
        size: Size.Medium,
        uid: '323 - B',
      }),
      breedRepository.create({
        name: 'Perro de Pastor Mallorquin',
        size: Size.Large,
        uid: '334 - C',
      }),
      breedRepository.create({ name: 'Perro de Pastor Vasco', size: Size.Large, uid: '66 - B' }),
      breedRepository.create({
        name: 'Perro de Presa Mallorquin',
        size: Size.Large,
        uid: '134 - B',
      }),
      breedRepository.create({
        name: 'Perro Majorero (Bardino Majorero)',
        size: Size.Large,
        uid: '377',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Small)',
        size: Size.Small,
        uid: '378 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Medium)',
        size: Size.Small,
        uid: '379 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Large)',
        size: Size.Medium,
        uid: '380 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Small)',
        size: Size.Small,
        uid: '378 - A',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Medium)',
        size: Size.Small,
        uid: '379 - A',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Large)',
        size: Size.Medium,
        uid: '380 - A',
      }),
      breedRepository.create({
        name: 'Petit Basset Griffon Vendeen',
        size: Size.Medium,
        uid: '250',
      }),
      breedRepository.create({ name: 'Petit Bleu de Gascogne', size: Size.Medium, uid: '69 - A' }),
      breedRepository.create({ name: 'Petit Brabancon', size: Size.Small, uid: '125 - C' }),
      breedRepository.create({ name: 'Phalene', size: Size.Small, uid: '370 - C' }),
      breedRepository.create({ name: 'Pharaoh Hound', size: Size.Medium, uid: '381' }),
      breedRepository.create({ name: 'Phu Quoc Ridgeback', size: Size.Medium, uid: '382' }),
      breedRepository.create({ name: 'Picardy Shepherd', size: Size.Medium, uid: '85 - B' }),
      breedRepository.create({
        name: 'Picardy Spaniel (Epagneul Picard)',
        size: Size.Medium,
        uid: '383',
      }),
      breedRepository.create({
        name: 'Piccolo Lepraiolo Italiano',
        size: Size.Medium,
        uid: '454 - B',
      }),
      breedRepository.create({ name: 'Plott Hound', size: Size.Medium, uid: '384' }),
      breedRepository.create({ name: 'Podenco Andaluz (Large)', size: Size.Large, uid: '387 - A' }),
      breedRepository.create({
        name: 'Podenco Andaluz (Medium)',
        size: Size.Medium,
        uid: '386 - A',
      }),
      breedRepository.create({ name: 'Podenco Andaluz (Small)', size: Size.Small, uid: '385 - A' }),
      breedRepository.create({ name: 'Podenco Canario', size: Size.Medium, uid: '388 - A' }),
      breedRepository.create({ name: 'Podenco Ibicenco', size: Size.Medium, uid: '274 - B' }),
      breedRepository.create({ name: 'Podenco Maneto', size: Size.Small, uid: '389' }),
      breedRepository.create({ name: 'Podenco Valenciano', size: Size.Medium, uid: '390 - A' }),
      breedRepository.create({ name: 'Pointer (English Pointer)', size: Size.Large, uid: '391' }),
      breedRepository.create({ name: 'Poitevin', size: Size.Large, uid: '392' }),
      breedRepository.create({
        name: 'Polish Greyhound (Chart Polski)',
        size: Size.Large,
        uid: '393',
      }),
      breedRepository.create({ name: 'Polish Hound (Ogar Polski)', size: Size.Large, uid: '394' }),
      breedRepository.create({
        name: 'Polish Hunting Dog (Gonczy Polski)',
        size: Size.Medium,
        uid: '395',
      }),
      breedRepository.create({
        name: 'Polish Lowland Sheepdog',
        size: Size.Medium,
        uid: '396 - A',
      }),
      breedRepository.create({
        name: 'Polski Owczarek Nizinny',
        size: Size.Medium,
        uid: '396 - B',
      }),
      breedRepository.create({ name: 'Poltalloch Terrier', size: Size.Small, uid: '521 - B' }),
      breedRepository.create({ name: 'Pomapoo', size: Size.Small, uid: '9980' }),
      breedRepository.create({ name: 'Pomchi', size: Size.Small, uid: '9981 - A' }),
      breedRepository.create({ name: 'Pomeranian', size: Size.Small, uid: '242 - A' }),
      breedRepository.create({ name: 'Pomsky', size: Size.Small, uid: '9982' }),
      breedRepository.create({ name: 'Pont-Audemer Spaniel', size: Size.Medium, uid: '397 - A' }),
      breedRepository.create({ name: 'Poochon', size: Size.Small, uid: '9983 - A' }),
      breedRepository.create({ name: 'Poodle (Toy)', size: Size.Small, uid: '398' }),
      breedRepository.create({ name: 'Poodle (Miniature)', size: Size.Small, uid: '399' }),
      breedRepository.create({ name: 'Poodle (Standard)', size: Size.Large, uid: '400' }),
      breedRepository.create({ name: 'Poongsan Dog', size: Size.Large, uid: '415 - B' }),
      breedRepository.create({ name: 'Porcelaine', size: Size.Medium, uid: '401 - A' }),
      breedRepository.create({ name: 'Portuguese Cattle Dog', size: Size.Large, uid: '145 - B' }),
      breedRepository.create({
        name: 'Portuguese Podengo (Pequeno / Small)',
        size: Size.Small,
        uid: '404 - A',
      }),
      breedRepository.create({
        name: 'Portuguese Podengo (Medio / Medium) ',
        size: Size.Medium,
        uid: '403 - A',
      }),
      breedRepository.create({
        name: 'Portuguese Podengo (Grande / Large)',
        size: Size.Medium,
        uid: '402 - A',
      }),
      breedRepository.create({ name: 'Portuguese Pointer', size: Size.Medium, uid: '405' }),
      breedRepository.create({ name: 'Portuguese Sheepdog', size: Size.Medium, uid: '406' }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Small)',
        size: Size.Small,
        uid: '404 - B',
      }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Medium)',
        size: Size.Medium,
        uid: '403 - B',
      }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Large)',
        size: Size.Medium,
        uid: '402 - B',
      }),
      breedRepository.create({ name: 'Portuguese Water Dog', size: Size.Medium, uid: '407' }),
      breedRepository.create({ name: 'Posavac Hound', size: Size.Medium, uid: '408' }),
      breedRepository.create({ name: 'Prague Ratter', size: Size.Small, uid: '409 - A' }),
      breedRepository.create({ name: 'Prazsky Krysarik', size: Size.Small, uid: '409 - B' }),
      breedRepository.create({ name: 'Presa Canario', size: Size.Large, uid: '410' }),
      breedRepository.create({ name: 'Pudelpointer', size: Size.Large, uid: '411' }),
      breedRepository.create({ name: 'Pug', size: Size.Small, uid: '412' }),
      breedRepository.create({ name: 'Puggle', size: Size.Small, uid: '9984' }),
      breedRepository.create({ name: 'Puginese', size: Size.Small, uid: '9985' }),
      breedRepository.create({ name: 'Puli', size: Size.Medium, uid: '413' }),
      breedRepository.create({ name: 'Pumi', size: Size.Small, uid: '414' }),
      breedRepository.create({ name: 'Pungsan Dog', size: Size.Large, uid: '415 - A' }),
      breedRepository.create({ name: 'Pyrenean Mastiff', size: Size.Large, uid: '416' }),
      breedRepository.create({ name: 'Pyrenean Mountain Dog', size: Size.Large, uid: '254 - B' }),
      breedRepository.create({ name: 'Pyrenean Shepherd ', size: Size.Small, uid: '417 - A' }),
      breedRepository.create({ name: 'Queensland Heeler', size: Size.Medium, uid: '48 - B' }),
      breedRepository.create({ name: 'Rafeiro do Alentejo', size: Size.Large, uid: '418 - A' }),
      breedRepository.create({
        name: 'Rastreador Brasileiro (Brazilian Tracker)',
        size: Size.Large,
        uid: '419',
      }),
      breedRepository.create({ name: 'Rat Terrier', size: Size.Small, uid: '420' }),
      breedRepository.create({ name: 'Ratonero Bodeguero Andaluz', size: Size.Small, uid: '421' }),
      breedRepository.create({ name: 'Ratonero Mallorquin', size: Size.Small, uid: '333 - C' }),
      breedRepository.create({ name: 'Ratonero Murciano', size: Size.Small, uid: '422 - A' }),
      breedRepository.create({ name: 'Ratonero Valenciano ', size: Size.Small, uid: '511' }),
      breedRepository.create({ name: 'Red Heeler', size: Size.Medium, uid: '48 - D' }),
      breedRepository.create({ name: 'Redbone Coonhound', size: Size.Large, uid: '423' }),
      breedRepository.create({ name: 'Redtick Coonhound', size: Size.Large, uid: '26 - B' }),
      breedRepository.create({ name: 'Rhodesian Ridgeback', size: Size.Large, uid: '424' }),
      breedRepository.create({ name: 'Riesenschnauzer', size: Size.Large, uid: '450 - B' }),
      breedRepository.create({ name: 'Romagna Water Dog', size: Size.Medium, uid: '313 - B' }),
      breedRepository.create({
        name: 'Romanian Carpathian Shepherd',
        size: Size.Large,
        uid: '425',
      }),
      breedRepository.create({
        name: 'Romanian Mioritic Shepherd Dog',
        size: Size.Large,
        uid: '426',
      }),
      breedRepository.create({ name: 'Romanian Raven Shepherd Dog', size: Size.Large, uid: '427' }),
      breedRepository.create({ name: 'Rottweiler', size: Size.Large, uid: '428' }),
      breedRepository.create({ name: 'Russell Terrier', size: Size.Small, uid: '429' }),
      breedRepository.create({ name: 'Russian Spaniel', size: Size.Small, uid: '430' }),
      breedRepository.create({ name: 'Russian Tsvetnaya Bolonka', size: Size.Small, uid: '431' }),
      breedRepository.create({ name: 'Russian Wolfhound', size: Size.Large, uid: '110 - B' }),
      breedRepository.create({ name: 'Russian-European Laika', size: Size.Medium, uid: '433 - B' }),
      breedRepository.create({ name: 'Russkiy Toy (Russian Toy)', size: Size.Small, uid: '432' }),
      breedRepository.create({ name: 'Russo-European Laika', size: Size.Medium, uid: '433 - A' }),
      breedRepository.create({ name: 'Saarloos Wolfdog', size: Size.Large, uid: '434 - A' }),
      breedRepository.create({ name: 'Saarlooswolfhond', size: Size.Large, uid: '434 - B' }),
      breedRepository.create({
        name: 'Sabueso Espanol (Spanish Hound)',
        size: Size.Medium,
        uid: '435',
      }),
      breedRepository.create({ name: 'Saint Bernard', size: Size.Large, uid: '436' }),
      breedRepository.create({ name: 'Saint Germain Pointer', size: Size.Medium, uid: '120 - B' }),
      breedRepository.create({ name: 'Saint Miguel Cattle Dog', size: Size.Large, uid: '437' }),
      breedRepository.create({ name: 'Saint-Usuge Spaniel', size: Size.Medium, uid: '439 - A' }),
      breedRepository.create({ name: 'Saluki', size: Size.Medium, uid: '440' }),
      breedRepository.create({ name: 'Samoyed', size: Size.Medium, uid: '441' }),
      breedRepository.create({ name: 'Sapsali (Sapsaree)', size: Size.Medium, uid: '442' }),
      breedRepository.create({ name: 'Sarabi (Persian Mastiff)', size: Size.Large, uid: '443' }),
      breedRepository.create({ name: 'Sarplaninac', size: Size.Large, uid: '444 - A' }),
      breedRepository.create({
        name: 'Schapendoes (Dutch Sheepdog)',
        size: Size.Medium,
        uid: '445',
      }),
      breedRepository.create({ name: 'Schiller Hound', size: Size.Medium, uid: '446 - B' }),
      breedRepository.create({ name: 'Schillerstovare', size: Size.Medium, uid: '446 - A' }),
      breedRepository.create({ name: 'Schipperke', size: Size.Small, uid: '447' }),
      breedRepository.create({ name: 'Schnauzer (Miniature)', size: Size.Small, uid: '448 - A' }),
      breedRepository.create({ name: 'Schnauzer (Standard)', size: Size.Medium, uid: '449 - A' }),
      breedRepository.create({ name: 'Schnauzer (Giant)', size: Size.Large, uid: '450 - A' }),
      breedRepository.create({
        name: 'Schnoodle (Toy / Miniature)',
        size: Size.Small,
        uid: '9986',
      }),
      breedRepository.create({ name: 'Schnoodle (Standard)', size: Size.Medium, uid: '9987' }),
      breedRepository.create({ name: 'Schnoodle (Giant)', size: Size.Large, uid: '9988' }),
      breedRepository.create({
        name: 'Schwyz Hound (Swiss Hound)',
        size: Size.Medium,
        uid: '88 - B',
      }),
      breedRepository.create({
        name: 'Schwyzer Laufhund (Schweizer Laufhund)',
        size: Size.Medium,
        uid: '88 - A',
      }),
      breedRepository.create({
        name: 'Schwyzer Niederlaufhund (Schweizer Niederlaufhund)',
        size: Size.Small,
        uid: '92 - A',
      }),
      breedRepository.create({ name: 'Scottish Deerhound', size: Size.Large, uid: '451' }),
      breedRepository.create({ name: 'Scottish Terrier', size: Size.Small, uid: '452' }),
      breedRepository.create({ name: 'Sealyham Terrier', size: Size.Small, uid: '453' }),
      breedRepository.create({ name: "Segugio dell'Appennino", size: Size.Medium, uid: '454 - A' }),
      breedRepository.create({ name: 'Segugio Italiano', size: Size.Medium, uid: '455' }),
      breedRepository.create({ name: 'Segugio Maremmano', size: Size.Medium, uid: '456' }),
      breedRepository.create({ name: 'Seppala Siberian Sleddog ', size: Size.Medium, uid: '457' }),
      breedRepository.create({
        name: 'Serbian Hound (Srpski Gonic)',
        size: Size.Medium,
        uid: '458',
      }),
      breedRepository.create({
        name: 'Serbian Tricolour Hound (Srpski Trobojni Gonic)',
        size: Size.Medium,
        uid: '459',
      }),
      breedRepository.create({ name: 'Serrano Bulldog', size: Size.Large, uid: '460' }),
      breedRepository.create({ name: 'Shar-Pei', size: Size.Medium, uid: '461' }),
      breedRepository.create({ name: 'Sheepadoodle (Micro / Toy)', size: Size.Small, uid: '9989' }),
      breedRepository.create({
        name: 'Sheepadoodle (Miniature / Medium)',
        size: Size.Medium,
        uid: '9990',
      }),
      breedRepository.create({ name: 'Sheepadoodle (Standard)', size: Size.Large, uid: '9991' }),
      breedRepository.create({ name: 'Shetland Sheepdog (Sheltie)', size: Size.Small, uid: '462' }),
      breedRepository.create({ name: 'Shiba Inu', size: Size.Small, uid: '463' }),
      breedRepository.create({ name: 'Shichon', size: Size.Small, uid: '9997 - B' }),
      breedRepository.create({ name: 'Shih Tzu', size: Size.Small, uid: '464' }),
      breedRepository.create({ name: 'Shih-Poo', size: Size.Small, uid: '9992' }),
      breedRepository.create({ name: 'Shikoku', size: Size.Medium, uid: '465' }),
      breedRepository.create({ name: 'Shorkie', size: Size.Small, uid: '9993 - A' }),
      breedRepository.create({ name: 'Shorkie Tzu', size: Size.Small, uid: '9993 - B' }),
      breedRepository.create({ name: 'Siberian Husky', size: Size.Medium, uid: '466' }),
      breedRepository.create({ name: 'Silken Windhound', size: Size.Medium, uid: '467' }),
      breedRepository.create({ name: 'Silky Terrier', size: Size.Small, uid: '468' }),
      breedRepository.create({ name: 'Skye Terrier', size: Size.Medium, uid: '469' }),
      breedRepository.create({ name: 'Sloughi', size: Size.Medium, uid: '470' }),
      breedRepository.create({ name: 'Slovac Cuvac', size: Size.Large, uid: '472 - B' }),
      breedRepository.create({ name: 'Slovakian Chuvach', size: Size.Large, uid: '472 - C' }),
      breedRepository.create({ name: 'Slovakian Hound', size: Size.Medium, uid: '473 - B' }),
      breedRepository.create({
        name: 'Slovakian Rough-Haired Pointer',
        size: Size.Large,
        uid: '471 - B',
      }),
      breedRepository.create({
        name: 'Slovakian Wirehaired Pointer',
        size: Size.Large,
        uid: '471 - A',
      }),
      breedRepository.create({ name: 'Slovensky Cuvac', size: Size.Large, uid: '472 - A' }),
      breedRepository.create({ name: 'Slovensky Kopov', size: Size.Medium, uid: '473 - A' }),
      breedRepository.create({ name: 'Smaland Hound', size: Size.Medium, uid: '474 - B' }),
      breedRepository.create({ name: 'Smalandsstovare', size: Size.Medium, uid: '474 - A' }),
      breedRepository.create({
        name: 'Small Bernese Hound (Small Swiss Hound)',
        size: Size.Small,
        uid: '90 - B',
      }),
      breedRepository.create({ name: 'Small Blue Gascony', size: Size.Medium, uid: '69 - B' }),
      breedRepository.create({
        name: 'Small French-English Hound',
        size: Size.Medium,
        uid: '37 - C',
      }),
      breedRepository.create({
        name: 'Small Greek Domestic Dog',
        size: Size.Small,
        uid: '304 - B',
      }),
      breedRepository.create({
        name: 'Small Jura Hound (Small Swiss Hound)',
        size: Size.Small,
        uid: '91 - B',
      }),
      breedRepository.create({
        name: 'Small Lucerne Hound (Small Swiss Hound)',
        size: Size.Small,
        uid: '93 - B',
      }),
      breedRepository.create({ name: 'Small Munsterlander', size: Size.Medium, uid: '319' }),
      breedRepository.create({
        name: 'Small Schwyz Hound (Small Swiss Hound)',
        size: Size.Small,
        uid: '92 - B',
      }),
      breedRepository.create({ name: 'Smooth Fox Terrier', size: Size.Small, uid: '476' }),
      breedRepository.create({
        name: 'Soft-Coated Wheaten Terrier',
        size: Size.Medium,
        uid: '478',
      }),
      breedRepository.create({ name: 'South Russian Ovcharka', size: Size.Large, uid: '479 - A' }),
      breedRepository.create({
        name: 'South Russian Shepherd Dog ',
        size: Size.Large,
        uid: '479 - B',
      }),
      breedRepository.create({ name: 'Spanish Mastiff ', size: Size.Large, uid: '480 - A' }),
      breedRepository.create({ name: 'Spanish Pointer', size: Size.Large, uid: '133 - B' }),
      breedRepository.create({ name: 'Spanish Water Dog', size: Size.Medium, uid: '481 - A' }),
      breedRepository.create({ name: 'Spino degli Iblei', size: Size.Large, uid: '482' }),
      breedRepository.create({
        name: 'Spinone Italiano (Italian Spinone)',
        size: Size.Large,
        uid: '483',
      }),
      breedRepository.create({ name: 'Sporting Lucas Terrier', size: Size.Small, uid: '328' }),
      breedRepository.create({ name: 'Stabyhoun (Stabijhoun)', size: Size.Medium, uid: '484' }),
      breedRepository.create({ name: 'Staffordshire Bull Terrier', size: Size.Medium, uid: '485' }),
      breedRepository.create({ name: 'Stephens Cur', size: Size.Medium, uid: '486 - C' }),
      breedRepository.create({ name: 'Stephens Stock', size: Size.Medium, uid: '486 - A' }),
      breedRepository.create({
        name: 'Stephens Stock Mountain Cur',
        size: Size.Medium,
        uid: '486 - B',
      }),
      breedRepository.create({
        name: 'Styrian Coarse-Haired Hound',
        size: Size.Medium,
        uid: '487',
      }),
      breedRepository.create({ name: 'Suomenajokoira', size: Size.Medium, uid: '217 - B' }),
      breedRepository.create({ name: 'Suomenlapinkoira', size: Size.Medium, uid: '218 - B' }),
      breedRepository.create({ name: 'Sussex Spaniel', size: Size.Medium, uid: '488' }),
      breedRepository.create({ name: 'Swedish Foxhound', size: Size.Large, uid: '265 - C' }),
      breedRepository.create({ name: 'Swedish Lapphund', size: Size.Medium, uid: '489' }),
      breedRepository.create({ name: 'Swedish Vallhund', size: Size.Small, uid: '490 - A' }),
      breedRepository.create({ name: 'Taiwan Dog', size: Size.Medium, uid: '221 - B' }),
      breedRepository.create({ name: 'Tamaskan Dog', size: Size.Large, uid: '491' }),
      breedRepository.create({ name: 'Tang Dog (唐狗)', size: Size.Medium, uid: '9998 - D' }),
      breedRepository.create({ name: 'Tatra Chuvach', size: Size.Large, uid: '472 - D' }),
      breedRepository.create({ name: 'Tatra Shepherd Dog', size: Size.Large, uid: '492 - A' }),
      breedRepository.create({ name: 'Teddy Roosevelt Terrier', size: Size.Small, uid: '493' }),
      breedRepository.create({ name: 'Telomian', size: Size.Small, uid: '494' }),
      breedRepository.create({ name: 'Tenterfield Terrier', size: Size.Small, uid: '495' }),
      breedRepository.create({ name: 'Thai Bangkaew', size: Size.Medium, uid: '496' }),
      breedRepository.create({ name: 'Thai Ridgeback', size: Size.Medium, uid: '497' }),
      breedRepository.create({ name: 'Tibetan Mastiff ', size: Size.Large, uid: '498' }),
      breedRepository.create({ name: 'Tibetan Spaniel ', size: Size.Small, uid: '499' }),
      breedRepository.create({ name: 'Tibetan Terrier ', size: Size.Small, uid: '500' }),
      breedRepository.create({ name: 'Tiroler Bracke', size: Size.Medium, uid: '508 - B' }),
      breedRepository.create({ name: 'Tong Gau (唐狗)', size: Size.Medium, uid: '9998 - E' }),
      breedRepository.create({ name: 'Tornjak', size: Size.Large, uid: '501 - A' }),
      breedRepository.create({ name: 'Tosa Inu', size: Size.Large, uid: '502 - A' }),
      breedRepository.create({ name: 'Toy Fox Terrier', size: Size.Small, uid: '475 - B' }),
      breedRepository.create({ name: 'Transmontano Mastiff', size: Size.Large, uid: '146 - B' }),
      breedRepository.create({ name: 'Transylvanian Hound', size: Size.Large, uid: '503' }),
      breedRepository.create({ name: 'Treeing Cur', size: Size.Medium, uid: '504' }),
      breedRepository.create({ name: 'Treeing Feist', size: Size.Small, uid: '348 - B' }),
      breedRepository.create({ name: 'Treeing Tennessee Brindle', size: Size.Medium, uid: '505' }),
      breedRepository.create({ name: 'Treeing Walker Coonhound', size: Size.Large, uid: '506' }),
      breedRepository.create({ name: 'Trigg Hound', size: Size.Medium, uid: '507' }),
      breedRepository.create({ name: 'Tuareg Sloughi', size: Size.Medium, uid: '58 - B' }),
      breedRepository.create({ name: 'Turkish Kangal Shepherd ', size: Size.Large, uid: '293' }),
      breedRepository.create({ name: 'Turkish Mastiff', size: Size.Large, uid: '9 - B' }),
      breedRepository.create({ name: 'Tyrolean Hound', size: Size.Medium, uid: '508 - A' }),
      breedRepository.create({
        name: 'Unknown Mixed Breed (唐狗)',
        size: Size.Medium,
        uid: '9998 - C',
      }),
      breedRepository.create({ name: 'Utonagan', size: Size.Large, uid: '9994' }),
      breedRepository.create({ name: 'Valencian Terrier', size: Size.Small, uid: '509' }),
      breedRepository.create({ name: 'Vitespitz', size: Size.Medium, uid: '59 - B' }),
      breedRepository.create({ name: 'Vizigothic Spitz', size: Size.Small, uid: '490 - B' }),
      breedRepository.create({ name: 'Vizsla ', size: Size.Medium, uid: '512' }),
      breedRepository.create({
        name: 'Volpino Italiano (Italian Volpino)',
        size: Size.Small,
        uid: '514',
      }),
      breedRepository.create({ name: 'Weimaraner', size: Size.Large, uid: '515' }),
      breedRepository.create({ name: 'Welsh Corgi (Cardigan)', size: Size.Small, uid: '516' }),
      breedRepository.create({ name: 'Welsh Corgi (Pembroke)', size: Size.Small, uid: '517' }),
      breedRepository.create({ name: 'Welsh Hound', size: Size.Large, uid: '518' }),
      breedRepository.create({ name: 'Welsh Springer Spaniel', size: Size.Medium, uid: '519' }),
      breedRepository.create({ name: 'Welsh Terrier', size: Size.Small, uid: '520' }),
      breedRepository.create({
        name: 'West Highland White Terrier (Westie)',
        size: Size.Small,
        uid: '521 - A',
      }),
      breedRepository.create({ name: 'West Siberian Laika', size: Size.Medium, uid: '522' }),
      breedRepository.create({ name: 'Westphalian Dachsbracke', size: Size.Medium, uid: '523' }),
      breedRepository.create({ name: 'Wetterhoun', size: Size.Large, uid: '524 - A' }),
      breedRepository.create({ name: 'Whippet', size: Size.Small, uid: '325' }),
      breedRepository.create({ name: 'White Shepherd', size: Size.Large, uid: '84 - C' }),
      breedRepository.create({ name: 'White Swiss Shepherd ', size: Size.Large, uid: '84 - B' }),
      breedRepository.create({ name: 'Wire Fox Terrier', size: Size.Small, uid: '477' }),
      breedRepository.create({
        name: 'Wirehaired Pointing Griffon',
        size: Size.Medium,
        uid: '525 - A',
      }),
      breedRepository.create({ name: 'Wirehaired Vizsla', size: Size.Medium, uid: '513' }),
      breedRepository.create({ name: 'Wolfspitz', size: Size.Medium, uid: '241 - B' }),
      breedRepository.create({ name: 'Xarnego Valenciano', size: Size.Medium, uid: '390 - B' }),
      breedRepository.create({ name: 'Xiasi Dog (Xiasi Quan)', size: Size.Medium, uid: '526' }),
      breedRepository.create({ name: 'Xoloitzcuintli (Toy)', size: Size.Small, uid: '340 - B' }),
      breedRepository.create({
        name: 'Xoloitzcuintli (Miniature)',
        size: Size.Small,
        uid: '341 - B',
      }),
      breedRepository.create({
        name: 'Xoloitzcuintli (Standard)',
        size: Size.Medium,
        uid: '342 - B',
      }),
      breedRepository.create({ name: 'Yakutian Laika', size: Size.Medium, uid: '527' }),
      breedRepository.create({ name: 'Yoranian', size: Size.Small, uid: '9995 - A' }),
      breedRepository.create({ name: 'Yorkie Pom', size: Size.Small, uid: '9995 - B' }),
      breedRepository.create({ name: 'Yorkie Tzu', size: Size.Small, uid: '9993 - C' }),
      breedRepository.create({ name: 'Yorkie-Chi', size: Size.Small, uid: '9957 - B' }),
      breedRepository.create({ name: 'Yorkiepoo', size: Size.Small, uid: '9996' }),
      breedRepository.create({ name: 'Yorkshire Terrier (Yorkie)', size: Size.Small, uid: '528' }),
      breedRepository.create({ name: 'Yorktese', size: Size.Small, uid: '9977 - B' }),
      breedRepository.create({
        name: 'Yugoslavian Shepherd Dog – Sharplanina',
        size: Size.Large,
        uid: '444 - B',
      }),
      breedRepository.create({ name: 'Zuchon', size: Size.Small, uid: '9997 - A' }),
      breedRepository.create({ name: 'Zwergschnauzer', size: Size.Small, uid: '448 - B' }),
      breedRepository.create({ name: 'Zwergspitz', size: Size.Small, uid: '242 - C' }),
    ];

    await breedRepository.save(breeds);
  }
}
