import { QueryRunner } from 'typeorm';

import Seeder from './Seeder';

import { Breed } from '@/entities';

export default class BreedSeeder extends Seeder {
  /**
   * Clean the Collection
   */
  async clean(queryRunner: QueryRunner): Promise<void> {
    const breedRepository = queryRunner.manager.getRepository(Breed);
    await breedRepository.remove(await breedRepository.find());
  }

  async run(queryRunner: QueryRunner): Promise<void> {
    const breedRepository = queryRunner.manager.getRepository(Breed);

    const breeds = [
      breedRepository.create({ name: 'Affenpinscher', size: 'Small', uid: '1' }),
      breedRepository.create({ name: 'Afghan Hound', size: 'Large', uid: '2' }),
      breedRepository.create({ name: 'Afghan Shepherd', size: 'Large', uid: '309 - B' }),
      breedRepository.create({ name: 'Africanis', size: 'Large', uid: '3' }),
      breedRepository.create({ name: 'Aidi', size: 'Medium', uid: '4 - A' }),
      breedRepository.create({ name: 'Airedale Terrier', size: 'Medium', uid: '5' }),
      breedRepository.create({ name: 'Akbash', size: 'Large', uid: '6' }),
      breedRepository.create({ name: 'Akita (American)', size: 'Large', uid: '7' }),
      breedRepository.create({ name: 'Akita (Japanese)', size: 'Large', uid: '8' }),
      breedRepository.create({ name: 'Aksaray Malaklisi', size: 'Large', uid: '9 - A' }),
      breedRepository.create({ name: 'Alano Espanol', size: 'Large', uid: '10' }),
      breedRepository.create({ name: 'Alapaha Blue Blood Bulldog', size: 'Large', uid: '11' }),
      breedRepository.create({ name: 'Alaskan Husky', size: 'Medium', uid: '12' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Toy)', size: 'Small', uid: '13' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Miniature)', size: 'Small', uid: '14' }),
      breedRepository.create({ name: 'Alaskan Klee Kai (Standard)', size: 'Small', uid: '15' }),
      breedRepository.create({ name: 'Alaskan Malador', size: 'Large', uid: '9940' }),
      breedRepository.create({ name: 'Alaskan Malamute', size: 'Large', uid: '16' }),
      breedRepository.create({ name: 'Alentejo Mastiff', size: 'Large', uid: '418 - B' }),
      breedRepository.create({ name: 'Alopekis', size: 'Small', uid: '17' }),
      breedRepository.create({ name: 'Alpine Dachsbracke', size: 'Medium', uid: '18' }),
      breedRepository.create({ name: 'Altamaha Plantation Dog', size: 'Large', uid: '38 - B' }),
      breedRepository.create({ name: 'American Alsatian', size: 'Large', uid: '19' }),
      breedRepository.create({ name: 'American Bulldog', size: 'Large', uid: '20' }),
      breedRepository.create({ name: 'American Bully (Pocket)', size: 'Medium', uid: '21' }),
      breedRepository.create({
        name: 'American Bully (Standard / Classic)',
        size: 'Large',
        uid: '22',
      }),
      breedRepository.create({ name: 'American Bully (XL)', size: 'Large', uid: '23' }),
      breedRepository.create({ name: 'American Cocker Spaniel', size: 'Small', uid: '24' }),
      breedRepository.create({ name: 'American English Coonhound', size: 'Large', uid: '26 - A' }),
      breedRepository.create({
        name: 'American Eskimo Dog (Toy / Miniature)',
        size: 'Small',
        uid: '27',
      }),
      breedRepository.create({ name: 'American Eskimo Dog (Standard)', size: 'Medium', uid: '28' }),
      breedRepository.create({ name: 'American Foxhound', size: 'Large', uid: '29' }),
      breedRepository.create({ name: 'American Hairless Terrier', size: 'Small', uid: '30' }),
      breedRepository.create({ name: 'American Leopard Hound', size: 'Large', uid: '31' }),
      breedRepository.create({ name: 'American Mastiff', size: 'Large', uid: '32' }),
      breedRepository.create({ name: 'American Pit Bull Terrier', size: 'Medium', uid: '33' }),
      breedRepository.create({ name: 'American Staffordshire Terrier', size: 'Large', uid: '34' }),
      breedRepository.create({ name: 'American Water Spaniel', size: 'Medium', uid: '35' }),
      breedRepository.create({ name: 'American White Shepherd', size: 'Large', uid: '84 - D' }),
      breedRepository.create({ name: 'Anatolian Karabash Dog', size: 'Large', uid: '36 - B' }),
      breedRepository.create({ name: 'Anatolian Shepherd', size: 'Large', uid: '36 - A' }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Small)',
        size: 'Small',
        uid: '385 - B',
      }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Medium)',
        size: 'Medium',
        uid: '386 - B',
      }),
      breedRepository.create({
        name: 'Andalusian Warren Hound (Large)',
        size: 'Large',
        uid: '387 - B',
      }),
      breedRepository.create({
        name: 'Anglo-Francais de Petite Venerie',
        size: 'Medium',
        uid: '37 - A',
      }),
      breedRepository.create({ name: 'Antebellum Bulldog', size: 'Large', uid: '38 - A' }),
      breedRepository.create({ name: 'Appenzell Cattle Dog', size: 'Large', uid: '39 - C' }),
      breedRepository.create({ name: 'Appenzeller Mountain Dog', size: 'Large', uid: '39 - B' }),
      breedRepository.create({ name: 'Appenzeller Sennenhund', size: 'Large', uid: '39 - A' }),
      breedRepository.create({ name: 'Argentine Pila (Small)', size: 'Small', uid: '40' }),
      breedRepository.create({ name: 'Argentine Pila (Medium)', size: 'Small', uid: '41' }),
      breedRepository.create({ name: 'Argentine Pila (Large)', size: 'Medium', uid: '42' }),
      breedRepository.create({ name: 'Ariege Hound', size: 'Large', uid: '44 - B' }),
      breedRepository.create({ name: 'Ariege Pointer', size: 'Large', uid: '43 - A' }),
      breedRepository.create({ name: 'Ariegeois', size: 'Large', uid: '44 - A' }),
      breedRepository.create({ name: 'Armant', size: 'Medium', uid: '45' }),
      breedRepository.create({ name: 'Armenian Gampr', size: 'Large', uid: '46' }),
      breedRepository.create({ name: 'Artois Hound', size: 'Large', uid: '47 - A' }),
      breedRepository.create({ name: 'Atlas Mountain Dog', size: 'Medium', uid: '4 - B' }),
      breedRepository.create({
        name: 'Aussiedoodle (Toy / Miniature)',
        size: 'Small',
        uid: '9941 - A',
      }),
      breedRepository.create({ name: 'Aussiedoodle (Standard)', size: 'Large', uid: '9942 - A' }),
      breedRepository.create({
        name: 'Aussiepoo (Toy / Miniature)',
        size: 'Small',
        uid: '9941 - B',
      }),
      breedRepository.create({ name: 'Aussiepoo (Standard)', size: 'Large', uid: '9942 - B' }),
      breedRepository.create({ name: 'Australian Cattle Dog', size: 'Medium', uid: '48 - A' }),
      breedRepository.create({
        name: 'Australian Cobberdog (Miniature)',
        size: 'Small',
        uid: '9970 - B',
      }),
      breedRepository.create({
        name: 'Australian Cobberdog (Medium)',
        size: 'Medium',
        uid: '9971 - B',
      }),
      breedRepository.create({
        name: 'Australian Cobberdog (Standard)',
        size: 'Large',
        uid: '9972 - B',
      }),
      breedRepository.create({ name: 'Australian Kelpie', size: 'Medium', uid: '49' }),
      breedRepository.create({ name: 'Australian Koolie', size: 'Medium', uid: '50' }),
      breedRepository.create({
        name: 'Australian Shepherd (Toy / Miniature)',
        size: 'Small',
        uid: '51 - B',
      }),
      breedRepository.create({ name: 'Australian Shepherd (Standard)', size: 'Medium', uid: '52' }),
      breedRepository.create({
        name: 'Australian Stumpy Tail Cattle Dog',
        size: 'Medium',
        uid: '53',
      }),
      breedRepository.create({ name: 'Australian Terrier', size: 'Small', uid: '54' }),
      breedRepository.create({ name: 'Austrian Black and Tan Hound', size: 'Medium', uid: '55' }),
      breedRepository.create({ name: 'Austrian Pinscher', size: 'Medium', uid: '56' }),
      breedRepository.create({ name: 'Auvergne Pointer', size: 'Medium', uid: '57 - A' }),
      breedRepository.create({ name: 'Azawakh', size: 'Medium', uid: '58 - A' }),
      breedRepository.create({ name: 'Bac Ha Dog', size: 'Medium', uid: '59 - A' }),
      breedRepository.create({ name: 'Bakharwal', size: 'Large', uid: '60' }),
      breedRepository.create({ name: 'Bankhar Dog', size: 'Large', uid: '61' }),
      breedRepository.create({ name: 'Barak Hound', size: 'Medium', uid: '62 - A' }),
      breedRepository.create({ name: 'Barbado da Terceira', size: 'Medium', uid: '63' }),
      breedRepository.create({ name: 'Barbet', size: 'Medium', uid: '64' }),
      breedRepository.create({ name: 'Basenji', size: 'Small', uid: '65' }),
      breedRepository.create({ name: 'Basque Shepherd Dog', size: 'Large', uid: '66 - A' }),
      breedRepository.create({ name: 'Basset Artesien Normand', size: 'Medium', uid: '67' }),
      breedRepository.create({ name: 'Basset Bleu de Gascogne', size: 'Medium', uid: '68 - A' }),
      breedRepository.create({ name: 'Basset Fauve de Bretagne', size: 'Medium', uid: '71 - A' }),
      breedRepository.create({ name: 'Basset Hound', size: 'Medium', uid: '72' }),
      breedRepository.create({ name: 'Bavarian Mountain Hound', size: 'Medium', uid: '73 - B' }),
      breedRepository.create({
        name: 'Bavarian Mountain Scent Hound',
        size: 'Medium',
        uid: '73 - A',
      }),
      breedRepository.create({ name: 'Beagle ', size: 'Small', uid: '74' }),
      breedRepository.create({ name: 'Beagle Harrier', size: 'Medium', uid: '75' }),
      breedRepository.create({ name: 'Beagle-Chi', size: 'Small', uid: '9953 - B' }),
      breedRepository.create({ name: 'Beaglier', size: 'Small', uid: '9943' }),
      breedRepository.create({ name: 'Bearded Collie', size: 'Medium', uid: '76' }),
      breedRepository.create({ name: 'Beauce Sheep Dog', size: 'Large', uid: '77 - C' }),
      breedRepository.create({ name: 'Beauceron', size: 'Large', uid: '77 - A' }),
      breedRepository.create({ name: 'Bedlington Terrier', size: 'Small', uid: '78' }),
      breedRepository.create({ name: 'Belgian Shepherd (Groenendael)', size: 'Medium', uid: '79' }),
      breedRepository.create({ name: 'Belgian Shepherd (Laekenois)', size: 'Medium', uid: '80' }),
      breedRepository.create({ name: 'Belgian Shepherd (Malinois)', size: 'Large', uid: '81' }),
      breedRepository.create({ name: 'Belgian Shepherd (Tervuren)', size: 'Large', uid: '82' }),
      breedRepository.create({ name: 'Bergamasco Sheepdog', size: 'Large', uid: '83' }),
      breedRepository.create({ name: 'Berger Blanc Suisse', size: 'Large', uid: '84 - A' }),
      breedRepository.create({ name: 'Berger de Beauce', size: 'Large', uid: '77 - B' }),
      breedRepository.create({ name: 'Berger de Brie', size: 'Large', uid: '122 - B' }),
      breedRepository.create({ name: 'Berger des Pyrenees', size: 'Small', uid: '417 - B' }),
      breedRepository.create({ name: 'Berger Picard', size: 'Medium', uid: '85 - A' }),
      breedRepository.create({ name: 'Bernedoodle (Toy / Tiny)', size: 'Small', uid: '9944' }),
      breedRepository.create({ name: 'Bernedoodle (Miniature)', size: 'Medium', uid: '9945' }),
      breedRepository.create({ name: 'Bernedoodle (Standard)', size: 'Large', uid: '9946' }),
      breedRepository.create({
        name: 'Berner Laufhund (Schweizer Laufhund)',
        size: 'Medium',
        uid: '86 - A',
      }),
      breedRepository.create({
        name: 'Berner Niederlaufhund (Schweizer Niederlaufhund)',
        size: 'Small',
        uid: '90 - A',
      }),
      breedRepository.create({
        name: 'Bernese Hound (Swiss Hound)',
        size: 'Medium',
        uid: '86 - B',
      }),
      breedRepository.create({ name: 'Bernese Mountain Dog', size: 'Large', uid: '94' }),
      breedRepository.create({ name: 'Bichon Frise', size: 'Small', uid: '95' }),
      breedRepository.create({ name: 'Bichon Poo', size: 'Small', uid: '9983 - C' }),
      breedRepository.create({ name: 'Bichpoo', size: 'Small', uid: '9983 - B' }),
      breedRepository.create({ name: 'Biewer Terrier', size: 'Small', uid: '96' }),
      breedRepository.create({ name: 'Billy', size: 'Large', uid: '97' }),
      breedRepository.create({ name: 'Black and Tan Coonhound', size: 'Large', uid: '98' }),
      breedRepository.create({ name: 'Black Forest Hound', size: 'Medium', uid: '473 - C' }),
      breedRepository.create({ name: 'Black Mouth Cur', size: 'Medium', uid: '99' }),
      breedRepository.create({ name: 'Black Russian Terrier', size: 'Large', uid: '100' }),
      breedRepository.create({ name: 'Bloodhound', size: 'Large', uid: '101' }),
      breedRepository.create({ name: 'Blue Gascony Basset', size: 'Medium', uid: '68 - B' }),
      breedRepository.create({ name: 'Blue Gascony Griffon', size: 'Medium', uid: '260 - B' }),
      breedRepository.create({ name: 'Blue Heeler', size: 'Medium', uid: '48 - C' }),
      breedRepository.create({ name: 'Blue Lacy', size: 'Medium', uid: '102' }),
      breedRepository.create({ name: 'Blue Picardy Spaniel', size: 'Medium', uid: '103 - A' }),
      breedRepository.create({ name: 'Bluetick Coonhound', size: 'Large', uid: '104' }),
      breedRepository.create({ name: 'Boerboel', size: 'Large', uid: '105' }),
      breedRepository.create({ name: 'Bohemian Shepherd', size: 'Medium', uid: '106' }),
      breedRepository.create({ name: 'Bohemian Spotted Dog', size: 'Medium', uid: '156 - B' }),
      breedRepository.create({
        name: 'Bohemian Wirehaired Pointing Griffon',
        size: 'Large',
        uid: '155 - B',
      }),
      breedRepository.create({ name: 'Bolognese', size: 'Small', uid: '107' }),
      breedRepository.create({ name: 'Borador', size: 'Medium', uid: '9947' }),
      breedRepository.create({ name: 'Border Collie', size: 'Medium', uid: '108' }),
      breedRepository.create({ name: 'Border Terrier', size: 'Small', uid: '109' }),
      breedRepository.create({ name: 'Borzoi', size: 'Large', uid: '110 - A' }),
      breedRepository.create({
        name: 'Bosnian and Herzegovinian Croatian Shepherd Dog',
        size: 'Large',
        uid: '501 - B',
      }),
      breedRepository.create({
        name: 'Bosnian Broken Haired Hound',
        size: 'Medium',
        uid: '62 - B',
      }),
      breedRepository.create({
        name: 'Bosnian Coarse Haired Hound',
        size: 'Medium',
        uid: '62 - C',
      }),
      breedRepository.create({ name: 'Boston Terrier', size: 'Small', uid: '111' }),
      breedRepository.create({ name: 'Bourbonnais Pointer', size: 'Medium', uid: '117 - B' }),
      breedRepository.create({ name: 'Bouvier des Ardennes', size: 'Large', uid: '112' }),
      breedRepository.create({ name: 'Bouvier des Flandres', size: 'Large', uid: '113' }),
      breedRepository.create({ name: 'Boxer', size: 'Large', uid: '114' }),
      breedRepository.create({ name: 'Boykin Spaniel', size: 'Medium', uid: '115' }),
      breedRepository.create({ name: 'Bracco Italiano', size: 'Large', uid: '116 - A' }),
      breedRepository.create({ name: "Braque d'Auvergne", size: 'Medium', uid: '57 - B' }),
      breedRepository.create({ name: "Braque de l'Ariege", size: 'Large', uid: '43 - B' }),
      breedRepository.create({ name: 'Braque du Bourbonnais', size: 'Medium', uid: '117 - A' }),
      breedRepository.create({ name: 'Braque Francais (Gascogne)', size: 'Large', uid: '118 - A' }),
      breedRepository.create({
        name: 'Braque Francais (Pyrenean)',
        size: 'Medium',
        uid: '119 - A',
      }),
      breedRepository.create({
        name: 'Braque Francais de Grande Taille',
        size: 'Large',
        uid: '118 - C',
      }),
      breedRepository.create({
        name: 'Braque Francais de Petite Taille',
        size: 'Medium',
        uid: '119 - C',
      }),
      breedRepository.create({ name: 'Braque Saint Germain', size: 'Medium', uid: '120 - A' }),
      breedRepository.create({ name: 'Brazilian Terrier', size: 'Small', uid: '121' }),
      breedRepository.create({ name: 'Briard', size: 'Large', uid: '122 - A' }),
      breedRepository.create({ name: 'Briquet Griffon Vendeen', size: 'Medium', uid: '252' }),
      breedRepository.create({ name: 'Brittany', size: 'Medium', uid: '123' }),
      breedRepository.create({ name: 'Broholmer', size: 'Large', uid: '124 - A' }),
      breedRepository.create({ name: 'Brussels Griffon', size: 'Small', uid: '125 - A' }),
      breedRepository.create({ name: 'Bucovina Shepherd Dog', size: 'Large', uid: '126' }),
      breedRepository.create({
        name: 'Bulgarian Hound (Balgarski Barak)',
        size: 'Medium',
        uid: '127',
      }),
      breedRepository.create({
        name: 'Bulgarian Scenthound (Balgarsko Gonche)',
        size: 'Medium',
        uid: '128',
      }),
      breedRepository.create({ name: 'Bulgarian Shepherd Dog', size: 'Large', uid: '295 - B' }),
      breedRepository.create({ name: 'Bull Terrier', size: 'Medium', uid: '130' }),
      breedRepository.create({ name: 'Bull Terrier (Miniature)', size: 'Small', uid: '129' }),
      breedRepository.create({ name: 'Bullmastiff', size: 'Large', uid: '131' }),
      breedRepository.create({ name: 'Bullpug (Miniature Bulldog)', size: 'Medium', uid: '9948' }),
      breedRepository.create({ name: 'Bully Kutta', size: 'Large', uid: '132' }),
      breedRepository.create({ name: 'Burgos Pointer', size: 'Large', uid: '133 - A' }),
      breedRepository.create({ name: 'Ca de Bestiar', size: 'Large', uid: '334 - B' }),
      breedRepository.create({ name: 'Ca de Bou', size: 'Large', uid: '134 - A' }),
      breedRepository.create({ name: 'Ca Me Mallorqui', size: 'Medium', uid: '135' }),
      breedRepository.create({ name: 'Ca Rater Mallorqui', size: 'Small', uid: '333 - B' }),
      breedRepository.create({ name: 'Cairn Terrier', size: 'Small', uid: '136' }),
      breedRepository.create({ name: 'Calupoh', size: 'Large', uid: '137' }),
      breedRepository.create({ name: 'Campeiro Bulldog', size: 'Large', uid: '138' }),
      breedRepository.create({ name: 'Can de Palleiro', size: 'Large', uid: '139' }),
      breedRepository.create({ name: 'Canaan Dog', size: 'Medium', uid: '140' }),
      breedRepository.create({ name: 'Canadian Eskimo Dog', size: 'Large', uid: '141 - A' }),
      breedRepository.create({ name: 'Canadian Inuit Dog', size: 'Large', uid: '141 - B' }),
      breedRepository.create({ name: 'Canarian Warren Hound', size: 'Medium', uid: '388 - B' }),
      breedRepository.create({ name: 'Cane Corso', size: 'Large', uid: '142' }),
      breedRepository.create({ name: 'Cane di Oropa', size: 'Large', uid: '143' }),
      breedRepository.create({ name: 'Cantabrian Water Dog', size: 'Medium', uid: '144' }),
      breedRepository.create({ name: 'Cao da Serra da Estrela', size: 'Large', uid: '213 - B' }),
      breedRepository.create({ name: 'Cao de Castro Laboreiro', size: 'Large', uid: '145 - A' }),
      breedRepository.create({ name: 'Cao de Gado Transmontano', size: 'Large', uid: '146 - A' }),
      breedRepository.create({ name: 'Cao Fila de Sao Miguel', size: 'Large', uid: '438' }),
      breedRepository.create({ name: 'Carea Leones', size: 'Medium', uid: '147 - A' }),
      breedRepository.create({ name: 'Carolina Dog', size: 'Medium', uid: '148' }),
      breedRepository.create({ name: 'Castro Laboreiro Dog', size: 'Large', uid: '145 - C' }),
      breedRepository.create({ name: 'Catahoula Bulldog', size: 'Large', uid: '149' }),
      breedRepository.create({ name: 'Catahoula Leopard Dog', size: 'Large', uid: '150' }),
      breedRepository.create({ name: 'Catalan Sheepdog', size: 'Medium', uid: '151 - A' }),
      breedRepository.create({ name: 'Catalonian Sheepdog', size: 'Medium', uid: '151 - B' }),
      breedRepository.create({ name: 'Caucasian Mountain Dog', size: 'Large', uid: '152 - C' }),
      breedRepository.create({ name: 'Caucasian Ovcharka', size: 'Large', uid: '152 - B' }),
      breedRepository.create({ name: 'Caucasian Shepherd Dog ', size: 'Large', uid: '152 - A' }),
      breedRepository.create({ name: 'Cava-Lon', size: 'Small', uid: '9949' }),
      breedRepository.create({ name: 'Cavachon', size: 'Small', uid: '9950' }),
      breedRepository.create({ name: 'Cavadoodle', size: 'Small', uid: '9952 - B' }),
      breedRepository.create({ name: 'Cavador', size: 'Medium', uid: '9951' }),
      breedRepository.create({ name: 'Cavalier King Charles Spaniel', size: 'Small', uid: '153' }),
      breedRepository.create({ name: 'Cavapoo', size: 'Small', uid: '9952 - A' }),
      breedRepository.create({ name: 'Cavipoo', size: 'Small', uid: '9952 - D' }),
      breedRepository.create({ name: 'Cavoodle', size: 'Small', uid: '9952 - C' }),
      breedRepository.create({ name: 'Central Asian Shepherd Dog', size: 'Large', uid: '154' }),
      breedRepository.create({ name: 'Cesky Fousek', size: 'Large', uid: '155 - A' }),
      breedRepository.create({ name: 'Cesky Strakaty Pes', size: 'Medium', uid: '156 - A' }),
      breedRepository.create({ name: 'Cesky Terrier', size: 'Small', uid: '157' }),
      breedRepository.create({ name: 'Cheagle', size: 'Small', uid: '9953 - A' }),
      breedRepository.create({ name: 'Chesapeake Bay Retriever', size: 'Large', uid: '158' }),
      breedRepository.create({ name: 'Chi-Pom', size: 'Small', uid: '9981 - C' }),
      breedRepository.create({ name: "Chien d'Artois", size: 'Large', uid: '47 - B' }),
      breedRepository.create({ name: 'Chien de Franche-Comte', size: 'Medium', uid: '401 - B' }),
      breedRepository.create({ name: 'Chihuahua', size: 'Small', uid: '159' }),
      breedRepository.create({ name: 'Chilean Fox Terrier', size: 'Small', uid: '160 - A' }),
      breedRepository.create({ name: 'Chilean Terrier', size: 'Small', uid: '160 - B' }),
      breedRepository.create({ name: 'Chimeranian', size: 'Small', uid: '9981 - B' }),
      breedRepository.create({ name: 'Chinese Crested Dog', size: 'Small', uid: '161' }),
      breedRepository.create({
        name: 'Chinese Imperial Dog (Imperial Shih Tzu)',
        size: 'Small',
        uid: '162',
      }),
      breedRepository.create({ name: 'Chinook', size: 'Large', uid: '163' }),
      breedRepository.create({ name: 'Chion', size: 'Small', uid: '9954 - A' }),
      breedRepository.create({ name: 'Chipin', size: 'Small', uid: '9955' }),
      breedRepository.create({ name: 'Chippiparai', size: 'Medium', uid: '164' }),
      breedRepository.create({ name: 'Chiweenie', size: 'Small', uid: '9956' }),
      breedRepository.create({ name: 'Chongqing Dog', size: 'Medium', uid: '165' }),
      breedRepository.create({ name: 'Chorkie', size: 'Small', uid: '9957 - A' }),
      breedRepository.create({ name: 'Chortai', size: 'Large', uid: '166 - A' }),
      breedRepository.create({ name: 'Chow Chow', size: 'Large', uid: '167' }),
      breedRepository.create({ name: 'Chuandong Hound', size: 'Medium', uid: '168' }),
      breedRepository.create({ name: 'Chug', size: 'Small', uid: '9958' }),
      breedRepository.create({ name: 'Cimarron Uruguayo', size: 'Large', uid: '169' }),
      breedRepository.create({ name: "Cirneco dell'Etna", size: 'Small', uid: '170' }),
      breedRepository.create({ name: 'Clumber Spaniel', size: 'Large', uid: '171' }),
      breedRepository.create({ name: 'Cockalier', size: 'Small', uid: '9959' }),
      breedRepository.create({ name: 'Cockapoo (Toy / Miniature)', size: 'Small', uid: '9960' }),
      breedRepository.create({ name: 'Cockapoo (Maxi)', size: 'Medium', uid: '9961' }),
      breedRepository.create({ name: 'Collie (Rough)', size: 'Large', uid: '172' }),
      breedRepository.create({ name: 'Collie (Smooth)', size: 'Large', uid: '173' }),
      breedRepository.create({
        name: 'Colombian Fino Hound (Grande / Large)',
        size: 'Large',
        uid: '175',
      }),
      breedRepository.create({
        name: 'Colombian Fino Hound (Standard)',
        size: 'Medium',
        uid: '174',
      }),
      breedRepository.create({ name: 'Continental Bulldog', size: 'Large', uid: '176' }),
      breedRepository.create({ name: 'Continental Toy Spaniel', size: 'Small', uid: '370 - B' }),
      breedRepository.create({ name: 'Corgidor', size: 'Medium', uid: '9962' }),
      breedRepository.create({ name: 'Coton de Tulear', size: 'Small', uid: '177' }),
      breedRepository.create({ name: 'Cretan Hound', size: 'Medium', uid: '178' }),
      breedRepository.create({ name: 'Croatian Sheepdog', size: 'Medium', uid: '179' }),
      breedRepository.create({ name: 'Curly-Coated Retriever', size: 'Large', uid: '180' }),
      breedRepository.create({ name: 'Czech Spotted Dog', size: 'Medium', uid: '156 - C' }),
      breedRepository.create({ name: 'Czechoslovakian Vlcak', size: 'Large', uid: '181 - B' }),
      breedRepository.create({ name: 'Czechoslovakian Wolfdog', size: 'Large', uid: '181 - A' }),
      breedRepository.create({ name: 'Dachshund', size: 'Small', uid: '182' }),
      breedRepository.create({ name: 'Dalmatian', size: 'Large', uid: '183' }),
      breedRepository.create({ name: 'Dandie Dinmont Terrier', size: 'Small', uid: '184' }),
      breedRepository.create({ name: 'Danish Mastiff', size: 'Large', uid: '124 - B' }),
      breedRepository.create({ name: 'Danish Spitz', size: 'Medium', uid: '185' }),
      breedRepository.create({ name: 'Danish-Swedish Farmdog', size: 'Small', uid: '186' }),
      breedRepository.create({ name: 'Deutsch Drahthaar', size: 'Large', uid: '235 - B' }),
      breedRepository.create({ name: 'Deutsch Kurzhaar', size: 'Large', uid: '234 - B' }),
      breedRepository.create({ name: 'Deutsch Langhaar', size: 'Large', uid: '232 - B' }),
      breedRepository.create({ name: 'Deutsch Stichelhaar', size: 'Large', uid: '233 - B' }),
      breedRepository.create({
        name: 'Deutsche Bracke (German Hound)',
        size: 'Medium',
        uid: '187',
      }),
      breedRepository.create({
        name: 'Deutscher Wachtelhund (German Spaniel)',
        size: 'Medium',
        uid: '188',
      }),
      breedRepository.create({ name: 'Doberman Pinscher', size: 'Large', uid: '189 - A' }),
      breedRepository.create({ name: 'Dobermann', size: 'Large', uid: '189 - B' }),
      breedRepository.create({ name: 'Dogo Argentino', size: 'Large', uid: '190' }),
      breedRepository.create({ name: 'Dogo Guatemalteco', size: 'Large', uid: '191 - A' }),
      breedRepository.create({ name: 'Dogue Brasileiro', size: 'Large', uid: '192' }),
      breedRepository.create({ name: 'Dogue de Bordeaux', size: 'Large', uid: '193' }),
      breedRepository.create({ name: 'Donggyeongi (Daeng Gyeon)', size: 'Medium', uid: '194' }),
      breedRepository.create({ name: 'Doxiepoo', size: 'Small', uid: '9963' }),
      breedRepository.create({ name: 'Drentsche Patrijshond', size: 'Large', uid: '195 - A' }),
      breedRepository.create({ name: 'Drever', size: 'Medium', uid: '196' }),
      breedRepository.create({ name: 'Dunker (Norwegian Hound)', size: 'Medium', uid: '197' }),
      breedRepository.create({ name: 'Dutch Partridge Dog', size: 'Large', uid: '195 - B' }),
      breedRepository.create({ name: 'Dutch Shepherd', size: 'Large', uid: '198' }),
      breedRepository.create({ name: 'Dutch Smoushond', size: 'Small', uid: '199' }),
      breedRepository.create({ name: 'Dutch Tulip Hound', size: 'Small', uid: '338 - B' }),
      breedRepository.create({ name: 'Dwarf Spitz', size: 'Small', uid: '242 - B' }),
      breedRepository.create({ name: 'East European Shepherd', size: 'Large', uid: '200' }),
      breedRepository.create({ name: 'East Siberian Laika', size: 'Medium', uid: '201' }),
      breedRepository.create({ name: 'Eesti Hagijas', size: 'Medium', uid: '212 - B' }),
      breedRepository.create({ name: 'English Bulldog', size: 'Medium', uid: '202' }),
      breedRepository.create({ name: 'English Cocker Spaniel', size: 'Medium', uid: '25' }),
      breedRepository.create({ name: 'English Coonhound', size: 'Large', uid: '26 - C' }),
      breedRepository.create({ name: 'English Foxhound', size: 'Large', uid: '204' }),
      breedRepository.create({ name: 'English Mastiff', size: 'Large', uid: '205 - A' }),
      breedRepository.create({ name: 'English Setter', size: 'Large', uid: '206' }),
      breedRepository.create({ name: 'English Shepherd', size: 'Medium', uid: '207' }),
      breedRepository.create({ name: 'English Springer Spaniel', size: 'Medium', uid: '208' }),
      breedRepository.create({ name: 'English Toy Spaniel', size: 'Small', uid: '209 - A' }),
      breedRepository.create({
        name: 'English Toy Terrier (Black and Tan)',
        size: 'Small',
        uid: '210',
      }),
      breedRepository.create({ name: 'Entelbucher Cattle Dog', size: 'Medium', uid: '211 - B' }),
      breedRepository.create({ name: 'Entlebucher Mountain Dog', size: 'Medium', uid: '211 - A' }),
      breedRepository.create({ name: 'Epagneul Bleu de Picardie', size: 'Medium', uid: '103 - B' }),
      breedRepository.create({ name: 'Epagneul de Saint-Usuge', size: 'Medium', uid: '439 - B' }),
      breedRepository.create({ name: 'Epagneul Pont-Audemer', size: 'Medium', uid: '397 - B' }),
      breedRepository.create({ name: 'Estonian Hound', size: 'Medium', uid: '212 - A' }),
      breedRepository.create({ name: 'Estrela Mountain Dog', size: 'Large', uid: '213 - A' }),
      breedRepository.create({ name: 'Eurasier', size: 'Medium', uid: '214' }),
      breedRepository.create({ name: 'Euskal Artzain Txakurra ', size: 'Large', uid: '66 - C' }),
      breedRepository.create({ name: 'Fawn Brittany Basset', size: 'Medium', uid: '71 - B' }),
      breedRepository.create({ name: 'Fawn Brittany Griffon', size: 'Medium', uid: '261 - B' }),
      breedRepository.create({ name: 'Field Spaniel', size: 'Medium', uid: '215' }),
      breedRepository.create({
        name: 'Fila Brasileiro (Brazilian Mastiff)',
        size: 'Large',
        uid: '216',
      }),
      breedRepository.create({ name: 'Finnish Hound', size: 'Medium', uid: '217 - A' }),
      breedRepository.create({ name: 'Finnish Lapphund', size: 'Medium', uid: '218 - A' }),
      breedRepository.create({ name: 'Finnish Spitz', size: 'Small', uid: '219' }),
      breedRepository.create({ name: 'Flat Coated Retriever', size: 'Large', uid: '220' }),
      breedRepository.create({ name: 'Formosan Mountain Dog', size: 'Medium', uid: '221 - A' }),
      breedRepository.create({ name: 'Francais Blanc et Noir', size: 'Large', uid: '222 - A' }),
      breedRepository.create({ name: 'Francais Blanc et Orange', size: 'Large', uid: '223 - A' }),
      breedRepository.create({ name: 'Francais Tricolore', size: 'Large', uid: '224 - A' }),
      breedRepository.create({ name: 'French Bulldog', size: 'Small', uid: '225' }),
      breedRepository.create({
        name: 'French Pointing Dog (Gascogne)',
        size: 'Large',
        uid: '118 - B',
      }),
      breedRepository.create({
        name: 'French Pointing Dog (Pyrenean)',
        size: 'Medium',
        uid: '119 - B',
      }),
      breedRepository.create({
        name: 'French Spaniel (Epagneul Francais)',
        size: 'Medium',
        uid: '226',
      }),
      breedRepository.create({ name: 'French Tricolour Hound', size: 'Large', uid: '224 - B' }),
      breedRepository.create({
        name: 'French White and Black Hound',
        size: 'Large',
        uid: '222 - B',
      }),
      breedRepository.create({
        name: 'French White and Orange Hound',
        size: 'Large',
        uid: '223 - B',
      }),
      breedRepository.create({ name: 'Frisian Water Dog', size: 'Large', uid: '524 - B' }),
      breedRepository.create({
        name: 'Galgo Espanol (Spanish Greyhound)',
        size: 'Large',
        uid: '227',
      }),
      breedRepository.create({ name: 'Gascon Saintongeois (Grand)', size: 'Large', uid: '229' }),
      breedRepository.create({ name: 'Gascon Saintongeois (Petit)', size: 'Medium', uid: '228' }),
      breedRepository.create({ name: 'Gaucho Sheepdog', size: 'Large', uid: '230 - A' }),
      breedRepository.create({ name: 'Georgian Shepherd', size: 'Large', uid: '231' }),
      breedRepository.create({ name: 'German Longhaired Pointer', size: 'Large', uid: '232 - A' }),
      breedRepository.create({ name: 'German Pinscher', size: 'Medium', uid: '236' }),
      breedRepository.create({
        name: 'German Rough Haired Pointer',
        size: 'Large',
        uid: '233 - A',
      }),
      breedRepository.create({ name: 'German Shepherd (Alsatian)', size: 'Large', uid: '237' }),
      breedRepository.create({ name: 'German Shorthaired Pointer', size: 'Large', uid: '234 - A' }),
      breedRepository.create({
        name: 'German Spitz (Toy / Miniature)',
        size: 'Small',
        uid: '238 - A',
      }),
      breedRepository.create({ name: 'German Spitz (Medium)', size: 'Small', uid: '239 - A' }),
      breedRepository.create({
        name: 'German Spitz (Giant / Large)',
        size: 'Medium',
        uid: '240 - A',
      }),
      breedRepository.create({ name: 'German Wirehaired Pointer', size: 'Large', uid: '235 - A' }),
      breedRepository.create({ name: 'Glen of Imaal Terrier', size: 'Medium', uid: '243' }),
      breedRepository.create({ name: 'Goldador', size: 'Large', uid: '9964' }),
      breedRepository.create({ name: 'Golden Retriever', size: 'Large', uid: '244' }),
      breedRepository.create({
        name: 'Goldendoodle (Toy / Miniature)',
        size: 'Small',
        uid: '9965',
      }),
      breedRepository.create({ name: 'Goldendoodle (Standard)', size: 'Large', uid: '9966' }),
      breedRepository.create({ name: 'Gordon Setter', size: 'Large', uid: '245' }),
      breedRepository.create({ name: 'Gos Rater Valencia', size: 'Small', uid: '510' }),
      breedRepository.create({ name: 'Gran Mastin de Borinquen', size: 'Large', uid: '246' }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Blanc et Noir',
        size: 'Large',
        uid: '247 - A',
      }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Blanc et Orange',
        size: 'Large',
        uid: '248 - A',
      }),
      breedRepository.create({
        name: 'Grand Anglo-Francais Tricolore',
        size: 'Large',
        uid: '249 - A',
      }),
      breedRepository.create({ name: 'Grand Basset Griffon Vendeen', size: 'Medium', uid: '251' }),
      breedRepository.create({ name: 'Grand Bleu de Gascogne', size: 'Large', uid: '70 - A' }),
      breedRepository.create({
        name: 'Great Anglo-French Tricolour Hound',
        size: 'Large',
        uid: '249 - B',
      }),
      breedRepository.create({
        name: 'Great Anglo-French White and Black Hound',
        size: 'Large',
        uid: '247 - B',
      }),
      breedRepository.create({
        name: 'Great Anglo-French White and Orange Hound',
        size: 'Large',
        uid: '248 - B',
      }),
      breedRepository.create({ name: 'Great Dane', size: 'Large', uid: '253' }),
      breedRepository.create({ name: 'Great Gascony Blue', size: 'Large', uid: '70 - B' }),
      breedRepository.create({ name: 'Great Pyrenees', size: 'Large', uid: '254 - A' }),
      breedRepository.create({ name: 'Greater Swiss Mountain Dog', size: 'Large', uid: '255' }),
      breedRepository.create({ name: 'Greek Harehound', size: 'Medium', uid: '256 - A' }),
      breedRepository.create({ name: 'Greek Shepherd', size: 'Large', uid: '257' }),
      breedRepository.create({ name: 'Greenland Dog', size: 'Large', uid: '258' }),
      breedRepository.create({ name: 'Greyhound', size: 'Large', uid: '259' }),
      breedRepository.create({ name: 'Griffon Bleu de Gascogne', size: 'Medium', uid: '260 - A' }),
      breedRepository.create({ name: 'Griffon Bruxellois', size: 'Small', uid: '125 - B' }),
      breedRepository.create({ name: 'Griffon Fauve de Bretagne', size: 'Medium', uid: '261 - A' }),
      breedRepository.create({ name: 'Griffon Nivernais', size: 'Medium', uid: '262' }),
      breedRepository.create({ name: 'Großspitz (Gross Spitz)', size: 'Medium', uid: '240 - B' }),
      breedRepository.create({ name: 'Guatemalan Dogo', size: 'Large', uid: '191 - B' }),
      breedRepository.create({ name: 'Gull Dong', size: 'Large', uid: '263' }),
      breedRepository.create({ name: 'Halden Hound', size: 'Medium', uid: '264 - A' }),
      breedRepository.create({ name: 'Haldenstover', size: 'Medium', uid: '264 - B' }),
      breedRepository.create({ name: 'Hamilton Hound', size: 'Large', uid: '265 - B' }),
      breedRepository.create({ name: 'Hamiltonstovare', size: 'Large', uid: '265 - A' }),
      breedRepository.create({ name: 'Hannoverscher Schweisshund', size: 'Large', uid: '266 - C' }),
      breedRepository.create({ name: 'Hanoverian Hound', size: 'Large', uid: '266 - B' }),
      breedRepository.create({ name: 'Hanoverian Scenthound', size: 'Large', uid: '266 - A' }),
      breedRepository.create({ name: 'Harrier', size: 'Medium', uid: '267' }),
      breedRepository.create({ name: 'Havanese', size: 'Small', uid: '268' }),
      breedRepository.create({ name: 'Hellenic Hound', size: 'Medium', uid: '256 - B' }),
      breedRepository.create({ name: 'Hellinikos Ichnilatis', size: 'Medium', uid: '256 - C' }),
      breedRepository.create({ name: 'Hierran Wolfdog', size: 'Medium', uid: '323 - C' }),
      breedRepository.create({ name: 'Himalayan Sheepdog', size: 'Large', uid: '269' }),
      breedRepository.create({ name: 'Hmong Bobtail Dog', size: 'Medium', uid: '270 - A' }),
      breedRepository.create({ name: 'Hmong Docked Tail Dog', size: 'Medium', uid: '270 - B' }),
      breedRepository.create({ name: 'Hokkaido', size: 'Medium', uid: '271' }),
      breedRepository.create({ name: 'Hortaya Borzaya', size: 'Large', uid: '166 - B' }),
      breedRepository.create({ name: 'Hovawart', size: 'Large', uid: '272' }),
      breedRepository.create({
        name: 'Hungarian Greyhound (Magyar Agar) ',
        size: 'Large',
        uid: '331',
      }),
      breedRepository.create({ name: 'Hushan Dog', size: 'Medium', uid: '322 - B' }),
      breedRepository.create({ name: 'Huskador', size: 'Medium', uid: '9973 - B' }),
      breedRepository.create({ name: 'Hygenhund (Hygen Hound)', size: 'Medium', uid: '273' }),
      breedRepository.create({ name: 'Ibizan Hound', size: 'Medium', uid: '274 - A' }),
      breedRepository.create({ name: 'Ibizan Podenco', size: 'Medium', uid: '274 - C' }),
      breedRepository.create({ name: 'Icelandic Sheepdog', size: 'Medium', uid: '275' }),
      breedRepository.create({
        name: 'Indian Spitz (Smaller / Lesser)',
        size: 'Small',
        uid: '276',
      }),
      breedRepository.create({ name: 'Indian Spitz (Greater)', size: 'Medium', uid: '277' }),
      breedRepository.create({ name: 'Irish Doodle (Miniature)', size: 'Medium', uid: '9967' }),
      breedRepository.create({ name: 'Irish Doodle (Standard)', size: 'Large', uid: '9968' }),
      breedRepository.create({ name: 'Irish Red and White Setter', size: 'Medium', uid: '278' }),
      breedRepository.create({ name: 'Irish Setter', size: 'Large', uid: '279' }),
      breedRepository.create({ name: 'Irish Terrier', size: 'Medium', uid: '280' }),
      breedRepository.create({ name: 'Irish Water Spaniel', size: 'Medium', uid: '281' }),
      breedRepository.create({ name: 'Irish Wolfhound', size: 'Large', uid: '282' }),
      breedRepository.create({
        name: 'Istrian Coarse Haired Hound',
        size: 'Medium',
        uid: '283 - A',
      }),
      breedRepository.create({ name: 'Istrian Short Haired Hound', size: 'Medium', uid: '284' }),
      breedRepository.create({ name: 'Istrian Wirehaired Hound', size: 'Medium', uid: '283 - B' }),
      breedRepository.create({ name: 'Italian Greyhound', size: 'Small', uid: '285' }),
      breedRepository.create({ name: 'Italian Pointer', size: 'Large', uid: '116 - B' }),
      breedRepository.create({ name: 'Jack Russell Terrier', size: 'Small', uid: '286' }),
      breedRepository.create({
        name: 'Jagdterrier (German Hunting Terrier)',
        size: 'Small',
        uid: '287',
      }),
      breedRepository.create({ name: 'Jamthund (Swedish Elkhound)', size: 'Large', uid: '288' }),
      breedRepository.create({ name: 'Japanese Chin', size: 'Small', uid: '289 - A' }),
      breedRepository.create({ name: 'Japanese Mastiff', size: 'Large', uid: '502 - B' }),
      breedRepository.create({ name: 'Japanese Spaniel', size: 'Small', uid: '289 - B' }),
      breedRepository.create({ name: 'Japanese Spitz', size: 'Small', uid: '290' }),
      breedRepository.create({ name: 'Japanese Terrier', size: 'Small', uid: '291' }),
      breedRepository.create({ name: 'Jura Hound (Swiss Hound)', size: 'Medium', uid: '87 - B' }),
      breedRepository.create({
        name: 'Jura Laufhund (Schweizer Laufhund)',
        size: 'Medium',
        uid: '87 - A',
      }),
      breedRepository.create({
        name: 'Jura Niederlaufhund (Schweizer Niederlaufhund)',
        size: 'Small',
        uid: '91 - A',
      }),
      breedRepository.create({ name: 'Kai Ken', size: 'Medium', uid: '292' }),
      breedRepository.create({ name: 'Kanni', size: 'Medium', uid: '294' }),
      breedRepository.create({ name: 'Karakachan', size: 'Large', uid: '295 - A' }),
      breedRepository.create({ name: 'Karelian Bear Dog', size: 'Medium', uid: '296' }),
      breedRepository.create({ name: 'Karelo-Finnish Laika', size: 'Small', uid: '297' }),
      breedRepository.create({ name: 'Karst Shepherd', size: 'Large', uid: '298' }),
      breedRepository.create({ name: 'Keeshond', size: 'Medium', uid: '241 - A' }),
      breedRepository.create({ name: 'Kerry Beagle', size: 'Medium', uid: '299' }),
      breedRepository.create({ name: 'Kerry Blue Terrier', size: 'Medium', uid: '300' }),
      breedRepository.create({ name: 'King Charles Spaniel', size: 'Small', uid: '209 - B' }),
      breedRepository.create({ name: 'King Shepherd', size: 'Large', uid: '301' }),
      breedRepository.create({ name: 'Kintamani-Bali Dog', size: 'Medium', uid: '302' }),
      breedRepository.create({ name: 'Kishu Ken', size: 'Medium', uid: '303' }),
      breedRepository.create({ name: 'Kleinspitz', size: 'Small', uid: '238 - B' }),
      breedRepository.create({ name: 'Kokoni', size: 'Small', uid: '304 - A' }),
      breedRepository.create({ name: 'Komondor', size: 'Large', uid: '305' }),
      breedRepository.create({
        name: 'Korean Dosa Mastiff (Mee Kyun Dosa)',
        size: 'Large',
        uid: '306',
      }),
      breedRepository.create({ name: 'Korean Jindo', size: 'Medium', uid: '307' }),
      breedRepository.create({ name: 'Korean Phungsan', size: 'Large', uid: '415 - C' }),
      breedRepository.create({ name: 'Korthals Griffon', size: 'Medium', uid: '525 - B' }),
      breedRepository.create({ name: 'Kromfohrlander', size: 'Small', uid: '308' }),
      breedRepository.create({ name: 'Kuchi', size: 'Large', uid: '309 - A' }),
      breedRepository.create({ name: 'Kunming Wolfdog', size: 'Large', uid: '310' }),
      breedRepository.create({ name: 'Kuvasz', size: 'Large', uid: '311' }),
      breedRepository.create({ name: 'Kyi-Leo', size: 'Small', uid: '9969' }),
      breedRepository.create({ name: 'Labradoodle (Miniature)', size: 'Small', uid: '9970 - A' }),
      breedRepository.create({ name: 'Labradoodle (Medium)', size: 'Medium', uid: '9971 - A' }),
      breedRepository.create({ name: 'Labradoodle (Standard)', size: 'Large', uid: '9972 - A' }),
      breedRepository.create({ name: 'Labrador Retriever', size: 'Large', uid: '312' }),
      breedRepository.create({ name: 'Labsky', size: 'Medium', uid: '9973 - A' }),
      breedRepository.create({ name: 'Lagotto Romagnolo', size: 'Medium', uid: '313 - A' }),
      breedRepository.create({ name: 'Lakeland Terrier', size: 'Small', uid: '314' }),
      breedRepository.create({ name: 'Lancashire Heeler', size: 'Small', uid: '315' }),
      breedRepository.create({ name: 'Landseer', size: 'Large', uid: '316' }),
      breedRepository.create({ name: 'Lapinporokoira', size: 'Large', uid: '317 - B' }),
      breedRepository.create({ name: 'Lapponian Herder', size: 'Large', uid: '317 - A' }),
      breedRepository.create({ name: 'Large Munsterlander', size: 'Large', uid: '318' }),
      breedRepository.create({ name: 'Leonberger', size: 'Large', uid: '320' }),
      breedRepository.create({ name: 'Leonese Sheepdog', size: 'Medium', uid: '147 - B' }),
      breedRepository.create({ name: 'Lhasa Apso', size: 'Small', uid: '321' }),
      breedRepository.create({ name: 'Liangshan Hound', size: 'Medium', uid: '322 - A' }),
      breedRepository.create({ name: 'Lobito Herreno', size: 'Medium', uid: '323 - A' }),
      breedRepository.create({
        name: 'Longhaired Whippet (Silken Windsprite)',
        size: 'Small',
        uid: '324',
      }),
      breedRepository.create({ name: 'Lowchen ', size: 'Small', uid: '326' }),
      breedRepository.create({ name: 'Lucas Terrier', size: 'Small', uid: '327' }),
      breedRepository.create({
        name: 'Lucerne Hound (Swiss Hound)',
        size: 'Medium',
        uid: '89 - B',
      }),
      breedRepository.create({
        name: 'Lupo Italiano (Italian Wolfdog)',
        size: 'Large',
        uid: '329',
      }),
      breedRepository.create({
        name: 'Luzerner Laufhund (Schweizer Laufhund)',
        size: 'Medium',
        uid: '89 - A',
      }),
      breedRepository.create({
        name: 'Luzerner Niederlaufhund (Schweizer Niederlaufhund)',
        size: 'Small',
        uid: '93 - A',
      }),
      breedRepository.create({ name: 'Mackenzie River Husky', size: 'Large', uid: '330' }),
      breedRepository.create({ name: 'Majestic Tree Hound', size: 'Large', uid: '332' }),
      breedRepository.create({ name: 'Majorca Mastiff', size: 'Large', uid: '134 - C' }),
      breedRepository.create({ name: 'Majorca Ratter', size: 'Small', uid: '333 - A' }),
      breedRepository.create({ name: 'Majorca Shepherd Dog', size: 'Large', uid: '334 - A' }),
      breedRepository.create({ name: 'Malshi', size: 'Small', uid: '9974 - A' }),
      breedRepository.create({ name: 'Maltese', size: 'Small', uid: '335' }),
      breedRepository.create({ name: 'Maltese Shih Tzu', size: 'Small', uid: '9974 - B' }),
      breedRepository.create({ name: 'Maltipoo', size: 'Small', uid: '9975' }),
      breedRepository.create({ name: 'Manchester Terrier', size: 'Small', uid: '336' }),
      breedRepository.create({ name: 'Maremma Sheepdog', size: 'Large', uid: '337 - A' }),
      breedRepository.create({
        name: 'Maremmano-Abruzzese Sheepdog',
        size: 'Large',
        uid: '337 - B',
      }),
      breedRepository.create({ name: 'Markiesje', size: 'Small', uid: '338 - A' }),
      breedRepository.create({ name: 'Mastiff', size: 'Large', uid: '205 - B' }),
      breedRepository.create({ name: 'Mastin Espanol', size: 'Large', uid: '480 - B' }),
      breedRepository.create({ name: 'McNab', size: 'Medium', uid: '339' }),
      breedRepository.create({
        name: 'Medium Sized Anglo-French Hound',
        size: 'Medium',
        uid: '37 - B',
      }),
      breedRepository.create({ name: 'Meliteo Kinidio', size: 'Small', uid: '304 - C' }),
      breedRepository.create({ name: 'Mexican Hairless Dog (Toy)', size: 'Small', uid: '340 - A' }),
      breedRepository.create({
        name: 'Mexican Hairless Dog (Miniature)',
        size: 'Small',
        uid: '341 - A',
      }),
      breedRepository.create({
        name: 'Mexican Hairless Dog (Standard)',
        size: 'Medium',
        uid: '342 - A',
      }),
      breedRepository.create({ name: 'Mi-Ki (Miki)', size: 'Small', uid: '9976' }),
      breedRepository.create({ name: 'Miniature American Shepherd', size: 'Small', uid: '51 - A' }),
      breedRepository.create({ name: 'Miniature Fox Terrier', size: 'Small', uid: '475 - A' }),
      breedRepository.create({ name: 'Miniature Pinscher', size: 'Small', uid: '343' }),
      breedRepository.create({ name: 'Mittelschnauzer', size: 'Medium', uid: '449 - B' }),
      breedRepository.create({ name: 'Mittelspitz', size: 'Small', uid: '239 - B' }),
      breedRepository.create({ name: 'Molossus of Epirus', size: 'Large', uid: '344' }),
      breedRepository.create({ name: 'Mongrel (唐狗)', size: 'Medium', uid: '9998 - A' }),
      breedRepository.create({ name: 'Montenegrin Mountain Hound', size: 'Medium', uid: '345' }),
      breedRepository.create({ name: 'Morkie ', size: 'Small', uid: '9977 - A' }),
      breedRepository.create({ name: 'Moscow Watchdog', size: 'Large', uid: '346' }),
      breedRepository.create({ name: 'Mountain Cur', size: 'Medium', uid: '347' }),
      breedRepository.create({ name: 'Mountain Feist', size: 'Small', uid: '348 - A' }),
      breedRepository.create({ name: 'Mountain View Cur', size: 'Medium', uid: '349' }),
      breedRepository.create({ name: 'Mucuchies', size: 'Large', uid: '350' }),
      breedRepository.create({ name: 'Mudi', size: 'Small', uid: '351' }),
      breedRepository.create({ name: 'Murcian Ratter', size: 'Small', uid: '422 - B' }),
      breedRepository.create({ name: 'Mutt (唐狗)', size: 'Medium', uid: '9998 - B' }),
      breedRepository.create({
        name: 'Neapolitan Mastiff (Mastino Napoletano)',
        size: 'Large',
        uid: '352',
      }),
      breedRepository.create({ name: 'Nederlandse Kooikerhondje', size: 'Small', uid: '353' }),
      breedRepository.create({ name: 'New Zealand Heading Dog', size: 'Large', uid: '354' }),
      breedRepository.create({ name: 'New Zealand Huntaway', size: 'Large', uid: '355' }),
      breedRepository.create({ name: 'Newfoundland', size: 'Large', uid: '356' }),
      breedRepository.create({ name: 'Norfolk Terrier', size: 'Small', uid: '357' }),
      breedRepository.create({
        name: 'Norrbottenspets (Norrbottenspitz)',
        size: 'Small',
        uid: '358',
      }),
      breedRepository.create({ name: 'Northern Inuit Dog', size: 'Large', uid: '359' }),
      breedRepository.create({ name: 'Norwegian Buhund', size: 'Medium', uid: '360' }),
      breedRepository.create({ name: 'Norwegian Elkhound', size: 'Medium', uid: '361' }),
      breedRepository.create({ name: 'Norwegian Lundehund', size: 'Small', uid: '362' }),
      breedRepository.create({ name: 'Norwich Terrier', size: 'Small', uid: '363' }),
      breedRepository.create({
        name: 'Nova Scotia Duck Tolling Retriever',
        size: 'Medium',
        uid: '364',
      }),
      breedRepository.create({
        name: 'Nureongi (Korean Yellow Spitz)',
        size: 'Medium',
        uid: '365',
      }),
      breedRepository.create({ name: 'Old Danish Pointer', size: 'Large', uid: '366' }),
      breedRepository.create({ name: 'Old English Sheepdog', size: 'Large', uid: '367' }),
      breedRepository.create({
        name: 'Olde English Bulldogge (Old English Bulldog)',
        size: 'Large',
        uid: '203',
      }),
      breedRepository.create({ name: 'Otterhound', size: 'Large', uid: '368' }),
      breedRepository.create({ name: 'Ovejero Magallanico', size: 'Medium', uid: '373 - B' }),
      breedRepository.create({ name: 'Ovelheiro Gaucho', size: 'Large', uid: '230 - B' }),
      breedRepository.create({ name: 'Owczarek Podhalanski', size: 'Large', uid: '492 - B' }),
      breedRepository.create({ name: 'Pachon Navarro', size: 'Medium', uid: '369' }),
      breedRepository.create({ name: 'Papihuahua', size: 'Small', uid: '9954 - B' }),
      breedRepository.create({ name: 'Papillon', size: 'Small', uid: '370 - A' }),
      breedRepository.create({ name: 'Papshund', size: 'Small', uid: '9978' }),
      breedRepository.create({ name: 'Parson Russell Terrier', size: 'Small', uid: '371' }),
      breedRepository.create({ name: 'Patagonian Sheepdog', size: 'Medium', uid: '373 - A' }),
      breedRepository.create({ name: 'Patterdale Terrier', size: 'Small', uid: '374' }),
      breedRepository.create({ name: 'Peekapoo', size: 'Small', uid: '9979 - A' }),
      breedRepository.create({ name: 'Pekeapoo', size: 'Small', uid: '9979 - B' }),
      breedRepository.create({ name: 'Pekepoo', size: 'Small', uid: '9979 - C' }),
      breedRepository.create({ name: 'Pekingese', size: 'Small', uid: '375' }),
      breedRepository.create({ name: 'Perdigueiro Galego', size: 'Medium', uid: '376' }),
      breedRepository.create({ name: 'Perdiguero de Burgos', size: 'Large', uid: '133 - C' }),
      breedRepository.create({ name: 'Perro de Agua Espanol', size: 'Medium', uid: '481 - B' }),
      breedRepository.create({ name: 'Perro de Pastor Garafiano ', size: 'Large', uid: '372' }),
      breedRepository.create({ name: 'Perro de Pastor Herreno', size: 'Medium', uid: '323 - B' }),
      breedRepository.create({ name: 'Perro de Pastor Mallorquin', size: 'Large', uid: '334 - C' }),
      breedRepository.create({ name: 'Perro de Pastor Vasco', size: 'Large', uid: '66 - B' }),
      breedRepository.create({ name: 'Perro de Presa Mallorquin', size: 'Large', uid: '134 - B' }),
      breedRepository.create({
        name: 'Perro Majorero (Bardino Majorero)',
        size: 'Large',
        uid: '377',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Small)',
        size: 'Small',
        uid: '378 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Medium)',
        size: 'Small',
        uid: '379 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Hairless Dog (Large)',
        size: 'Medium',
        uid: '380 - B',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Small)',
        size: 'Small',
        uid: '378 - A',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Medium)',
        size: 'Small',
        uid: '379 - A',
      }),
      breedRepository.create({
        name: 'Peruvian Inca Orchid (Large)',
        size: 'Medium',
        uid: '380 - A',
      }),
      breedRepository.create({ name: 'Petit Basset Griffon Vendeen', size: 'Medium', uid: '250' }),
      breedRepository.create({ name: 'Petit Bleu de Gascogne', size: 'Medium', uid: '69 - A' }),
      breedRepository.create({ name: 'Petit Brabancon', size: 'Small', uid: '125 - C' }),
      breedRepository.create({ name: 'Phalene', size: 'Small', uid: '370 - C' }),
      breedRepository.create({ name: 'Pharaoh Hound', size: 'Medium', uid: '381' }),
      breedRepository.create({ name: 'Phu Quoc Ridgeback', size: 'Medium', uid: '382' }),
      breedRepository.create({ name: 'Picardy Shepherd', size: 'Medium', uid: '85 - B' }),
      breedRepository.create({
        name: 'Picardy Spaniel (Epagneul Picard)',
        size: 'Medium',
        uid: '383',
      }),
      breedRepository.create({
        name: 'Piccolo Lepraiolo Italiano',
        size: 'Medium',
        uid: '454 - B',
      }),
      breedRepository.create({ name: 'Plott Hound', size: 'Medium', uid: '384' }),
      breedRepository.create({ name: 'Podenco Andaluz (Large)', size: 'Large', uid: '387 - A' }),
      breedRepository.create({ name: 'Podenco Andaluz (Medium)', size: 'Medium', uid: '386 - A' }),
      breedRepository.create({ name: 'Podenco Andaluz (Small)', size: 'Small', uid: '385 - A' }),
      breedRepository.create({ name: 'Podenco Canario', size: 'Medium', uid: '388 - A' }),
      breedRepository.create({ name: 'Podenco Ibicenco', size: 'Medium', uid: '274 - B' }),
      breedRepository.create({ name: 'Podenco Maneto', size: 'Small', uid: '389' }),
      breedRepository.create({ name: 'Podenco Valenciano', size: 'Medium', uid: '390 - A' }),
      breedRepository.create({ name: 'Pointer (English Pointer)', size: 'Large', uid: '391' }),
      breedRepository.create({ name: 'Poitevin', size: 'Large', uid: '392' }),
      breedRepository.create({
        name: 'Polish Greyhound (Chart Polski)',
        size: 'Large',
        uid: '393',
      }),
      breedRepository.create({ name: 'Polish Hound (Ogar Polski)', size: 'Large', uid: '394' }),
      breedRepository.create({
        name: 'Polish Hunting Dog (Gonczy Polski)',
        size: 'Medium',
        uid: '395',
      }),
      breedRepository.create({ name: 'Polish Lowland Sheepdog', size: 'Medium', uid: '396 - A' }),
      breedRepository.create({ name: 'Polski Owczarek Nizinny', size: 'Medium', uid: '396 - B' }),
      breedRepository.create({ name: 'Poltalloch Terrier', size: 'Small', uid: '521 - B' }),
      breedRepository.create({ name: 'Pomapoo', size: 'Small', uid: '9980' }),
      breedRepository.create({ name: 'Pomchi', size: 'Small', uid: '9981 - A' }),
      breedRepository.create({ name: 'Pomeranian', size: 'Small', uid: '242 - A' }),
      breedRepository.create({ name: 'Pomsky', size: 'Small', uid: '9982' }),
      breedRepository.create({ name: 'Pont-Audemer Spaniel', size: 'Medium', uid: '397 - A' }),
      breedRepository.create({ name: 'Poochon', size: 'Small', uid: '9983 - A' }),
      breedRepository.create({ name: 'Poodle (Toy)', size: 'Small', uid: '398' }),
      breedRepository.create({ name: 'Poodle (Miniature)', size: 'Small', uid: '399' }),
      breedRepository.create({ name: 'Poodle (Standard)', size: 'Large', uid: '400' }),
      breedRepository.create({ name: 'Poongsan Dog', size: 'Large', uid: '415 - B' }),
      breedRepository.create({ name: 'Porcelaine', size: 'Medium', uid: '401 - A' }),
      breedRepository.create({ name: 'Portuguese Cattle Dog', size: 'Large', uid: '145 - B' }),
      breedRepository.create({
        name: 'Portuguese Podengo (Pequeno / Small)',
        size: 'Small',
        uid: '404 - A',
      }),
      breedRepository.create({
        name: 'Portuguese Podengo (Medio / Medium) ',
        size: 'Medium',
        uid: '403 - A',
      }),
      breedRepository.create({
        name: 'Portuguese Podengo (Grande / Large)',
        size: 'Medium',
        uid: '402 - A',
      }),
      breedRepository.create({ name: 'Portuguese Pointer', size: 'Medium', uid: '405' }),
      breedRepository.create({ name: 'Portuguese Sheepdog', size: 'Medium', uid: '406' }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Small)',
        size: 'Small',
        uid: '404 - B',
      }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Medium)',
        size: 'Medium',
        uid: '403 - B',
      }),
      breedRepository.create({
        name: 'Portuguese Warren Hound (Large)',
        size: 'Medium',
        uid: '402 - B',
      }),
      breedRepository.create({ name: 'Portuguese Water Dog', size: 'Medium', uid: '407' }),
      breedRepository.create({ name: 'Posavac Hound', size: 'Medium', uid: '408' }),
      breedRepository.create({ name: 'Prague Ratter', size: 'Small', uid: '409 - A' }),
      breedRepository.create({ name: 'Prazsky Krysarik', size: 'Small', uid: '409 - B' }),
      breedRepository.create({ name: 'Presa Canario', size: 'Large', uid: '410' }),
      breedRepository.create({ name: 'Pudelpointer', size: 'Large', uid: '411' }),
      breedRepository.create({ name: 'Pug', size: 'Small', uid: '412' }),
      breedRepository.create({ name: 'Puggle', size: 'Small', uid: '9984' }),
      breedRepository.create({ name: 'Puginese', size: 'Small', uid: '9985' }),
      breedRepository.create({ name: 'Puli', size: 'Medium', uid: '413' }),
      breedRepository.create({ name: 'Pumi', size: 'Small', uid: '414' }),
      breedRepository.create({ name: 'Pungsan Dog', size: 'Large', uid: '415 - A' }),
      breedRepository.create({ name: 'Pyrenean Mastiff', size: 'Large', uid: '416' }),
      breedRepository.create({ name: 'Pyrenean Mountain Dog', size: 'Large', uid: '254 - B' }),
      breedRepository.create({ name: 'Pyrenean Shepherd ', size: 'Small', uid: '417 - A' }),
      breedRepository.create({ name: 'Queensland Heeler', size: 'Medium', uid: '48 - B' }),
      breedRepository.create({ name: 'Rafeiro do Alentejo', size: 'Large', uid: '418 - A' }),
      breedRepository.create({
        name: 'Rastreador Brasileiro (Brazilian Tracker)',
        size: 'Large',
        uid: '419',
      }),
      breedRepository.create({ name: 'Rat Terrier', size: 'Small', uid: '420' }),
      breedRepository.create({ name: 'Ratonero Bodeguero Andaluz', size: 'Small', uid: '421' }),
      breedRepository.create({ name: 'Ratonero Mallorquin', size: 'Small', uid: '333 - C' }),
      breedRepository.create({ name: 'Ratonero Murciano', size: 'Small', uid: '422 - A' }),
      breedRepository.create({ name: 'Ratonero Valenciano ', size: 'Small', uid: '511' }),
      breedRepository.create({ name: 'Red Heeler', size: 'Medium', uid: '48 - D' }),
      breedRepository.create({ name: 'Redbone Coonhound', size: 'Large', uid: '423' }),
      breedRepository.create({ name: 'Redtick Coonhound', size: 'Large', uid: '26 - B' }),
      breedRepository.create({ name: 'Rhodesian Ridgeback', size: 'Large', uid: '424' }),
      breedRepository.create({ name: 'Riesenschnauzer', size: 'Large', uid: '450 - B' }),
      breedRepository.create({ name: 'Romagna Water Dog', size: 'Medium', uid: '313 - B' }),
      breedRepository.create({ name: 'Romanian Carpathian Shepherd', size: 'Large', uid: '425' }),
      breedRepository.create({ name: 'Romanian Mioritic Shepherd Dog', size: 'Large', uid: '426' }),
      breedRepository.create({ name: 'Romanian Raven Shepherd Dog', size: 'Large', uid: '427' }),
      breedRepository.create({ name: 'Rottweiler', size: 'Large', uid: '428' }),
      breedRepository.create({ name: 'Russell Terrier', size: 'Small', uid: '429' }),
      breedRepository.create({ name: 'Russian Spaniel', size: 'Small', uid: '430' }),
      breedRepository.create({ name: 'Russian Tsvetnaya Bolonka', size: 'Small', uid: '431' }),
      breedRepository.create({ name: 'Russian Wolfhound', size: 'Large', uid: '110 - B' }),
      breedRepository.create({ name: 'Russian-European Laika', size: 'Medium', uid: '433 - B' }),
      breedRepository.create({ name: 'Russkiy Toy (Russian Toy)', size: 'Small', uid: '432' }),
      breedRepository.create({ name: 'Russo-European Laika', size: 'Medium', uid: '433 - A' }),
      breedRepository.create({ name: 'Saarloos Wolfdog', size: 'Large', uid: '434 - A' }),
      breedRepository.create({ name: 'Saarlooswolfhond', size: 'Large', uid: '434 - B' }),
      breedRepository.create({
        name: 'Sabueso Espanol (Spanish Hound)',
        size: 'Medium',
        uid: '435',
      }),
      breedRepository.create({ name: 'Saint Bernard', size: 'Large', uid: '436' }),
      breedRepository.create({ name: 'Saint Germain Pointer', size: 'Medium', uid: '120 - B' }),
      breedRepository.create({ name: 'Saint Miguel Cattle Dog', size: 'Large', uid: '437' }),
      breedRepository.create({ name: 'Saint-Usuge Spaniel', size: 'Medium', uid: '439 - A' }),
      breedRepository.create({ name: 'Saluki', size: 'Medium', uid: '440' }),
      breedRepository.create({ name: 'Samoyed', size: 'Medium', uid: '441' }),
      breedRepository.create({ name: 'Sapsali (Sapsaree)', size: 'Medium', uid: '442' }),
      breedRepository.create({ name: 'Sarabi (Persian Mastiff)', size: 'Large', uid: '443' }),
      breedRepository.create({ name: 'Sarplaninac', size: 'Large', uid: '444 - A' }),
      breedRepository.create({ name: 'Schapendoes (Dutch Sheepdog)', size: 'Medium', uid: '445' }),
      breedRepository.create({ name: 'Schiller Hound', size: 'Medium', uid: '446 - B' }),
      breedRepository.create({ name: 'Schillerstovare', size: 'Medium', uid: '446 - A' }),
      breedRepository.create({ name: 'Schipperke', size: 'Small', uid: '447' }),
      breedRepository.create({ name: 'Schnauzer (Miniature)', size: 'Small', uid: '448 - A' }),
      breedRepository.create({ name: 'Schnauzer (Standard)', size: 'Medium', uid: '449 - A' }),
      breedRepository.create({ name: 'Schnauzer (Giant)', size: 'Large', uid: '450 - A' }),
      breedRepository.create({ name: 'Schnoodle (Toy / Miniature)', size: 'Small', uid: '9986' }),
      breedRepository.create({ name: 'Schnoodle (Standard)', size: 'Medium', uid: '9987' }),
      breedRepository.create({ name: 'Schnoodle (Giant)', size: 'Large', uid: '9988' }),
      breedRepository.create({ name: 'Schwyz Hound (Swiss Hound)', size: 'Medium', uid: '88 - B' }),
      breedRepository.create({
        name: 'Schwyzer Laufhund (Schweizer Laufhund)',
        size: 'Medium',
        uid: '88 - A',
      }),
      breedRepository.create({
        name: 'Schwyzer Niederlaufhund (Schweizer Niederlaufhund)',
        size: 'Small',
        uid: '92 - A',
      }),
      breedRepository.create({ name: 'Scottish Deerhound', size: 'Large', uid: '451' }),
      breedRepository.create({ name: 'Scottish Terrier', size: 'Small', uid: '452' }),
      breedRepository.create({ name: 'Sealyham Terrier', size: 'Small', uid: '453' }),
      breedRepository.create({ name: "Segugio dell'Appennino", size: 'Medium', uid: '454 - A' }),
      breedRepository.create({ name: 'Segugio Italiano', size: 'Medium', uid: '455' }),
      breedRepository.create({ name: 'Segugio Maremmano', size: 'Medium', uid: '456' }),
      breedRepository.create({ name: 'Seppala Siberian Sleddog ', size: 'Medium', uid: '457' }),
      breedRepository.create({ name: 'Serbian Hound (Srpski Gonic)', size: 'Medium', uid: '458' }),
      breedRepository.create({
        name: 'Serbian Tricolour Hound (Srpski Trobojni Gonic)',
        size: 'Medium',
        uid: '459',
      }),
      breedRepository.create({ name: 'Serrano Bulldog', size: 'Large', uid: '460' }),
      breedRepository.create({ name: 'Shar-Pei', size: 'Medium', uid: '461' }),
      breedRepository.create({ name: 'Sheepadoodle (Micro / Toy)', size: 'Small', uid: '9989' }),
      breedRepository.create({
        name: 'Sheepadoodle (Miniature / Medium)',
        size: 'Medium',
        uid: '9990',
      }),
      breedRepository.create({ name: 'Sheepadoodle (Standard)', size: 'Large', uid: '9991' }),
      breedRepository.create({ name: 'Shetland Sheepdog (Sheltie)', size: 'Small', uid: '462' }),
      breedRepository.create({ name: 'Shiba Inu', size: 'Small', uid: '463' }),
      breedRepository.create({ name: 'Shichon', size: 'Small', uid: '9997 - B' }),
      breedRepository.create({ name: 'Shih Tzu', size: 'Small', uid: '464' }),
      breedRepository.create({ name: 'Shih-Poo', size: 'Small', uid: '9992' }),
      breedRepository.create({ name: 'Shikoku', size: 'Medium', uid: '465' }),
      breedRepository.create({ name: 'Shorkie', size: 'Small', uid: '9993 - A' }),
      breedRepository.create({ name: 'Shorkie Tzu', size: 'Small', uid: '9993 - B' }),
      breedRepository.create({ name: 'Siberian Husky', size: 'Medium', uid: '466' }),
      breedRepository.create({ name: 'Silken Windhound', size: 'Medium', uid: '467' }),
      breedRepository.create({ name: 'Silky Terrier', size: 'Small', uid: '468' }),
      breedRepository.create({ name: 'Skye Terrier', size: 'Medium', uid: '469' }),
      breedRepository.create({ name: 'Sloughi', size: 'Medium', uid: '470' }),
      breedRepository.create({ name: 'Slovac Cuvac', size: 'Large', uid: '472 - B' }),
      breedRepository.create({ name: 'Slovakian Chuvach', size: 'Large', uid: '472 - C' }),
      breedRepository.create({ name: 'Slovakian Hound', size: 'Medium', uid: '473 - B' }),
      breedRepository.create({
        name: 'Slovakian Rough-Haired Pointer',
        size: 'Large',
        uid: '471 - B',
      }),
      breedRepository.create({
        name: 'Slovakian Wirehaired Pointer',
        size: 'Large',
        uid: '471 - A',
      }),
      breedRepository.create({ name: 'Slovensky Cuvac', size: 'Large', uid: '472 - A' }),
      breedRepository.create({ name: 'Slovensky Kopov', size: 'Medium', uid: '473 - A' }),
      breedRepository.create({ name: 'Smaland Hound', size: 'Medium', uid: '474 - B' }),
      breedRepository.create({ name: 'Smalandsstovare', size: 'Medium', uid: '474 - A' }),
      breedRepository.create({
        name: 'Small Bernese Hound (Small Swiss Hound)',
        size: 'Small',
        uid: '90 - B',
      }),
      breedRepository.create({ name: 'Small Blue Gascony', size: 'Medium', uid: '69 - B' }),
      breedRepository.create({ name: 'Small French-English Hound', size: 'Medium', uid: '37 - C' }),
      breedRepository.create({ name: 'Small Greek Domestic Dog', size: 'Small', uid: '304 - B' }),
      breedRepository.create({
        name: 'Small Jura Hound (Small Swiss Hound)',
        size: 'Small',
        uid: '91 - B',
      }),
      breedRepository.create({
        name: 'Small Lucerne Hound (Small Swiss Hound)',
        size: 'Small',
        uid: '93 - B',
      }),
      breedRepository.create({ name: 'Small Munsterlander', size: 'Medium', uid: '319' }),
      breedRepository.create({
        name: 'Small Schwyz Hound (Small Swiss Hound)',
        size: 'Small',
        uid: '92 - B',
      }),
      breedRepository.create({ name: 'Smooth Fox Terrier', size: 'Small', uid: '476' }),
      breedRepository.create({ name: 'Soft-Coated Wheaten Terrier', size: 'Medium', uid: '478' }),
      breedRepository.create({ name: 'South Russian Ovcharka', size: 'Large', uid: '479 - A' }),
      breedRepository.create({
        name: 'South Russian Shepherd Dog ',
        size: 'Large',
        uid: '479 - B',
      }),
      breedRepository.create({ name: 'Spanish Mastiff ', size: 'Large', uid: '480 - A' }),
      breedRepository.create({ name: 'Spanish Pointer', size: 'Large', uid: '133 - B' }),
      breedRepository.create({ name: 'Spanish Water Dog', size: 'Medium', uid: '481 - A' }),
      breedRepository.create({ name: 'Spino degli Iblei', size: 'Large', uid: '482' }),
      breedRepository.create({
        name: 'Spinone Italiano (Italian Spinone)',
        size: 'Large',
        uid: '483',
      }),
      breedRepository.create({ name: 'Sporting Lucas Terrier', size: 'Small', uid: '328' }),
      breedRepository.create({ name: 'Stabyhoun (Stabijhoun)', size: 'Medium', uid: '484' }),
      breedRepository.create({ name: 'Staffordshire Bull Terrier', size: 'Medium', uid: '485' }),
      breedRepository.create({ name: 'Stephens Cur', size: 'Medium', uid: '486 - C' }),
      breedRepository.create({ name: 'Stephens Stock', size: 'Medium', uid: '486 - A' }),
      breedRepository.create({
        name: 'Stephens Stock Mountain Cur',
        size: 'Medium',
        uid: '486 - B',
      }),
      breedRepository.create({ name: 'Styrian Coarse-Haired Hound', size: 'Medium', uid: '487' }),
      breedRepository.create({ name: 'Suomenajokoira', size: 'Medium', uid: '217 - B' }),
      breedRepository.create({ name: 'Suomenlapinkoira', size: 'Medium', uid: '218 - B' }),
      breedRepository.create({ name: 'Sussex Spaniel', size: 'Medium', uid: '488' }),
      breedRepository.create({ name: 'Swedish Foxhound', size: 'Large', uid: '265 - C' }),
      breedRepository.create({ name: 'Swedish Lapphund', size: 'Medium', uid: '489' }),
      breedRepository.create({ name: 'Swedish Vallhund', size: 'Small', uid: '490 - A' }),
      breedRepository.create({ name: 'Taiwan Dog', size: 'Medium', uid: '221 - B' }),
      breedRepository.create({ name: 'Tamaskan Dog', size: 'Large', uid: '491' }),
      breedRepository.create({ name: 'Tang Dog (唐狗)', size: 'Medium', uid: '9998 - D' }),
      breedRepository.create({ name: 'Tatra Chuvach', size: 'Large', uid: '472 - D' }),
      breedRepository.create({ name: 'Tatra Shepherd Dog', size: 'Large', uid: '492 - A' }),
      breedRepository.create({ name: 'Teddy Roosevelt Terrier', size: 'Small', uid: '493' }),
      breedRepository.create({ name: 'Telomian', size: 'Small', uid: '494' }),
      breedRepository.create({ name: 'Tenterfield Terrier', size: 'Small', uid: '495' }),
      breedRepository.create({ name: 'Thai Bangkaew', size: 'Medium', uid: '496' }),
      breedRepository.create({ name: 'Thai Ridgeback', size: 'Medium', uid: '497' }),
      breedRepository.create({ name: 'Tibetan Mastiff ', size: 'Large', uid: '498' }),
      breedRepository.create({ name: 'Tibetan Spaniel ', size: 'Small', uid: '499' }),
      breedRepository.create({ name: 'Tibetan Terrier ', size: 'Small', uid: '500' }),
      breedRepository.create({ name: 'Tiroler Bracke', size: 'Medium', uid: '508 - B' }),
      breedRepository.create({ name: 'Tong Gau (唐狗)', size: 'Medium', uid: '9998 - E' }),
      breedRepository.create({ name: 'Tornjak', size: 'Large', uid: '501 - A' }),
      breedRepository.create({ name: 'Tosa Inu', size: 'Large', uid: '502 - A' }),
      breedRepository.create({ name: 'Toy Fox Terrier', size: 'Small', uid: '475 - B' }),
      breedRepository.create({ name: 'Transmontano Mastiff', size: 'Large', uid: '146 - B' }),
      breedRepository.create({ name: 'Transylvanian Hound', size: 'Large', uid: '503' }),
      breedRepository.create({ name: 'Treeing Cur', size: 'Medium', uid: '504' }),
      breedRepository.create({ name: 'Treeing Feist', size: 'Small', uid: '348 - B' }),
      breedRepository.create({ name: 'Treeing Tennessee Brindle', size: 'Medium', uid: '505' }),
      breedRepository.create({ name: 'Treeing Walker Coonhound', size: 'Large', uid: '506' }),
      breedRepository.create({ name: 'Trigg Hound', size: 'Medium', uid: '507' }),
      breedRepository.create({ name: 'Tuareg Sloughi', size: 'Medium', uid: '58 - B' }),
      breedRepository.create({ name: 'Turkish Kangal Shepherd ', size: 'Large', uid: '293' }),
      breedRepository.create({ name: 'Turkish Mastiff', size: 'Large', uid: '9 - B' }),
      breedRepository.create({ name: 'Tyrolean Hound', size: 'Medium', uid: '508 - A' }),
      breedRepository.create({
        name: 'Unknown Mixed Breed (唐狗)',
        size: 'Medium',
        uid: '9998 - C',
      }),
      breedRepository.create({ name: 'Utonagan', size: 'Large', uid: '9994' }),
      breedRepository.create({ name: 'Valencian Terrier', size: 'Small', uid: '509' }),
      breedRepository.create({ name: 'Vitespitz', size: 'Medium', uid: '59 - B' }),
      breedRepository.create({ name: 'Vizigothic Spitz', size: 'Small', uid: '490 - B' }),
      breedRepository.create({ name: 'Vizsla ', size: 'Medium', uid: '512' }),
      breedRepository.create({
        name: 'Volpino Italiano (Italian Volpino)',
        size: 'Small',
        uid: '514',
      }),
      breedRepository.create({ name: 'Weimaraner', size: 'Large', uid: '515' }),
      breedRepository.create({ name: 'Welsh Corgi (Cardigan)', size: 'Small', uid: '516' }),
      breedRepository.create({ name: 'Welsh Corgi (Pembroke)', size: 'Small', uid: '517' }),
      breedRepository.create({ name: 'Welsh Hound', size: 'Large', uid: '518' }),
      breedRepository.create({ name: 'Welsh Springer Spaniel', size: 'Medium', uid: '519' }),
      breedRepository.create({ name: 'Welsh Terrier', size: 'Small', uid: '520' }),
      breedRepository.create({
        name: 'West Highland White Terrier (Westie)',
        size: 'Small',
        uid: '521 - A',
      }),
      breedRepository.create({ name: 'West Siberian Laika', size: 'Medium', uid: '522' }),
      breedRepository.create({ name: 'Westphalian Dachsbracke', size: 'Medium', uid: '523' }),
      breedRepository.create({ name: 'Wetterhoun', size: 'Large', uid: '524 - A' }),
      breedRepository.create({ name: 'Whippet', size: 'Small', uid: '325' }),
      breedRepository.create({ name: 'White Shepherd', size: 'Large', uid: '84 - C' }),
      breedRepository.create({ name: 'White Swiss Shepherd ', size: 'Large', uid: '84 - B' }),
      breedRepository.create({ name: 'Wire Fox Terrier', size: 'Small', uid: '477' }),
      breedRepository.create({
        name: 'Wirehaired Pointing Griffon',
        size: 'Medium',
        uid: '525 - A',
      }),
      breedRepository.create({ name: 'Wirehaired Vizsla', size: 'Medium', uid: '513' }),
      breedRepository.create({ name: 'Wolfspitz', size: 'Medium', uid: '241 - B' }),
      breedRepository.create({ name: 'Xarnego Valenciano', size: 'Medium', uid: '390 - B' }),
      breedRepository.create({ name: 'Xiasi Dog (Xiasi Quan)', size: 'Medium', uid: '526' }),
      breedRepository.create({ name: 'Xoloitzcuintli (Toy)', size: 'Small', uid: '340 - B' }),
      breedRepository.create({ name: 'Xoloitzcuintli (Miniature)', size: 'Small', uid: '341 - B' }),
      breedRepository.create({ name: 'Xoloitzcuintli (Standard)', size: 'Medium', uid: '342 - B' }),
      breedRepository.create({ name: 'Yakutian Laika', size: 'Medium', uid: '527' }),
      breedRepository.create({ name: 'Yoranian', size: 'Small', uid: '9995 - A' }),
      breedRepository.create({ name: 'Yorkie Pom', size: 'Small', uid: '9995 - B' }),
      breedRepository.create({ name: 'Yorkie Tzu', size: 'Small', uid: '9993 - C' }),
      breedRepository.create({ name: 'Yorkie-Chi', size: 'Small', uid: '9957 - B' }),
      breedRepository.create({ name: 'Yorkiepoo', size: 'Small', uid: '9996' }),
      breedRepository.create({ name: 'Yorkshire Terrier (Yorkie)', size: 'Small', uid: '528' }),
      breedRepository.create({ name: 'Yorktese', size: 'Small', uid: '9977 - B' }),
      breedRepository.create({
        name: 'Yugoslavian Shepherd Dog – Sharplanina',
        size: 'Large',
        uid: '444 - B',
      }),
      breedRepository.create({ name: 'Zuchon', size: 'Small', uid: '9997 - A' }),
      breedRepository.create({ name: 'Zwergschnauzer', size: 'Small', uid: '448 - B' }),
      breedRepository.create({ name: 'Zwergspitz', size: 'Small', uid: '242 - C' }),
    ];

    await breedRepository.save(breeds);
  }
}
