import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Navigator from '@/components/Navigator';
import Notice from '@/components/Notice';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function AccountLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="min-h-screen bg-beige">
        <Notice />
        <Header nav={<Navigator />} />
        {children}
      </div>
      <Footer />
    </>
  );
}
